### ISSUE TITLE
speed up loading of mailing lists

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#113]
### as a developer, I need to speed up the loading of models in mailing lists with lots of users so that admin don't need to wait several minutes to see the list of subscribers and the site stays responsive during loading
---

### Tasks

- [ ] create database indexes for the display names of each Relationship in order to speed up fetch time

### Definition of Done

- [ ] even the most populated mailing lists load all Relationship field values in 20 seconds or less

### Resources

a list of all index suggestions made by mLab can be found [here](https://drive.google.com/file/d/1DCFHD7B6FHUm0BPNfjCR3TXWtgDebxxf/view?usp=sharing)

### Notes

performance may be improved by upgrading to Keystone 4.x

**Comment by bchiaruttini** [comment]
No longer relevant as lists will be kept in mailchimp
