### ISSUE TITLE
Family record pulling from incorrect status field

### ISSUE THREAD

**Issue by bchiaruttini** [mareinc/mare#126]
In the family record of homestudy registered families, the status field is pulling from Child Status List and should be pulling from Family Status List.

**Comment by bchiaruttini** [comment]
Correct statuses should be active, on hold, withdrawn and placed.

**Comment by bchiaruttini** [comment]
Families who had existing status of active now have no status indicated.  Families who had status of on hold, placed, withdrawn or disrupted appear to have their correct status.

**Comment by autoboxer** [comment]
@bchiaruttini, I can only run the script to map the previously selected statuses to the family status dropdown once this gets pushed to Production.

**Comment by bchiaruttini** [comment]
@autoboxer I am moving this from closed to Q&A as I am realizing we never completed the final step you reference earlier, which involves mapping previously selected statuses once pushed to production.  Can we add this final step to the To-Do list?  thanks.

**Comment by autoboxer** [comment]
Sure thing @bchiaruttini, let’s talk about during our Monday meeting.

**Comment by n-devr** [comment]
This is causing strange results in the child matching dashboard - only families that are incorrectly mapped to use the Child Statuses are being returned.  Any Family that has an actual Family Status applied to it will never be returned unless all status checkboxes are unchecked on the child matching page.

**Comment by n-devr** [comment]
We're removing status as a query parameter in child matching, but should still revisit this issue once Joe returns from vacation to determine if it needs to be addressed.
