### ISSUE TITLE
Add ability to save mid-stream while submitting child or family registration forms

### ISSUE THREAD

**Issue by bchiaruttini** [mareinc/mare#135]
Solution for user to save work they have done when not able to complete entire form.

**Comment by autoboxer** [comment]
If a social worker fill in any of the fields, then refreshes the page or visits it at a later date, they will see an option to restore their progress.  Clicking the restore button will refill the form.  Two things worth noting:

1. If the user is typing in a text box when they close the page, the contents of that text box won't be saved.

2. The details for children on the register a family form can't be repopulated without some messy code, but the rest of the form repopulates as expected.

**Comment by autoboxer** [comment]
@joesmare, when you're ready to test, let me know.  I'd like to turn emails back on to verify that all the fields are sent correctly as a few of the fields on the form needed to be changed for this to work.
