### ISSUE TITLE
Fully unlink sibs once they are no longer being recruited for together. 

### ISSUE THREAD

**Issue by bchiaruttini** [mareinc/mare#145]
When siblings are separated who were previously being recruited for together, and a family inquires about the now solo child, their confirmation of inquiry email still come through with both/all of the siblings listed.  (See 7059 who was connected to bro jonathan  and 6890/6891 who used be connected to 6933)

**Comment by autoboxer** [comment]
Arek, one place you might want to look if siblings aren't unlinking correctly is the mLab database (I think you have access, but can make sure you do if needed).  There was an issue in the past causing children to be added as a sibling more than once, so removing the sibling would only remove the first entry and they would still appear to be linked.

Example:

child1 has id 123
child2 has id 456

child2 is added as a sibling to child1, causing the **siblings** array for child1 to be `[456]`.  The issue we ran into in the past was child2 was being added twice, making the **siblings** array for child1 `[456, 456]`.  I hope that helps.

**Comment by bchiaruttini** [comment]
This resolved itself, potentially due to work on #183.
