### ISSUE TITLE
Additional fields in child record

### ISSUE THREAD

**Issue by bchiaruttini** [mareinc/mare#153]
In child's record, under agency information, should display adoption and recruitment worker's email and phone numbers.

**Comment by bchiaruttini** [comment]
@n-devr I don't see any changes here?

**Comment by n-devr** [comment]
@bchiaruttini Sorry for the confusion here - the additional fields are set in the `pre-save` hook of the model, so if you save a model you should see the new fields populate.  We'll need to run a script to save all of the Children models to force the fields to display.  I'll do a test run in `development`, but ultimately we'll have to choose an off-hours time to run an update script in `production`.

**Comment by n-devr** [comment]
So I ran a script in `dev` this afternoon and it looks like it worked for most of the chid records, but not all of them.  I'm not seeing errors so it must be failing silently, I'll look into that a bit more.  But you should be able to see the email and phone info on most records now, and if the data isn't populating for some reason a manual save will fix it.

**Comment by bchiaruttini** [comment]
looks good.

**Comment by n-devr** [comment]
I refined the script a bit and the update completed successfully in `dev` from what I can tell.  All of my spot checks have been good, but there's no feasible way to see if every Child record has been updated.  I had to comment out a lot of the `pre` and `post` save behavior in the Child model to allow the script to run properly, so we'll need to be deliberate in planning the update for `prod`.
