### ISSUE TITLE
Change treatment of SW registering a family's homestudy

### ISSUE THREAD

**Issue by bchiaruttini** [mareinc/mare#154]
When a SW registers a family's homestudy it should simply generate the email to the MARE worker, but not create a new account.  

Currently a worker is getting an error when they try to register homestudy of family who has existing account with same email.  Creating a form only that doesn't reference the system will prevent this from happening and MARE staff will crosswalk manually.   This could also be unnecessary if worker has ability to upload homestudy and totally eliminates need for form.

**Comment by bchiaruttini** [comment]
see #104

**Comment by bchiaruttini** [comment]
@autoboxer Please hold off on this story until we can speak  next week. It is related to #1 and I think makes sense to tackle together.  thanks

**Comment by bchiaruttini** [comment]
existing form can be found here: https://www.mareinc.org/register#family 

Changes to existing form should include:
-remove preferred contact method
- 'Submit Your Homestudy To complete your registration as a Massachusetts homestudied family, you must submit your homestudy to us via one of the following methods (choose one)' SHOULD READ: To complete registration of this Massachusetts homestudied family, please email a copy of license study to Liz Joyal at lizj@mareinc.org
-Remove Fax and Mailing address info
-Remove all Family Details and Adoption Preferences
-Register Homestudy Button should read Submit Registration

**Comment by n-devr** [comment]
### SW Family Registration Form Updates
https://www.mareinc.org/forms/social-worker-family-registration
 - [ ] remove preferred contact method
 - [ ] Submit Your Homestudy To complete your registration as a Massachusetts homestudied family, you must submit your homestudy to us via one of the following methods (choose one)' SHOULD READ: To complete registration of this Massachusetts homestudied family, please email a copy of license study to Liz Joyal at lizj@mareinc.org
 - [ ] Remove Fax and Mailing address info
 - [ ] Remove all Family Details and Adoption Preferences
 - [ ] Register Homestudy Button should read Submit Registration

### SW Family Registration Page Updates
https://www.mareinc.org/page/register-a-familys-homestudy
 - [ ] remove language: If you're a social worker, either log in or create an account.

**Comment by bchiaruttini** [comment]
Content  changes to Homestudy Registration Form: https://www.mareinc.org/forms/social-worker-family-registration.

-Remove all of the following intro: We are pleased that you are interested in registering your homestudied family with MARE. Only Massachusetts families with completed and approved homestudies can be registered with MARE through this form. Once registered, their criteria will be compared with the needs of the children registered with MARE to identify potential matches. When matches are identified, MARE will forward their homestudy to the child’s social worker. Follow-up on such referrals is at the discretion of the child’s social worker. There is no fee for this service.
If the family is not yet homestudied and would like to request information, please request that they fill out the Information Request Form.
For questions about Homestudy Registration, please contact Ricardo L Franco
Please Note
If you are unable to complete this form in one sitting, you can return at a later time to restore your work for this particular child registration form. You are not able to save work on multiple registrations at the same time.
-Replace with:  Please complete the form below to register the license study of an approved MA pre-adoptive family.  To complete the registration, a copy of the full license study must be emailed to Liz Joyal at lizj@mareinc.org.
-If possible, on a success message, prompt the user again to email a copy of the fully license study to Liz Joyal at lizj@mareinc.org

**Comment by bchiaruttini** [comment]
@n-devr.  I took a look and just a few small text changes before we push to production.
1.) We are changing so that all license studies should be sent to Ricardo Franco at ricardof@mareinc.org (instead of lizj).  So this change should be made in success banner, and at top and at bottom of form.
2.) Success banner title should read: Success. The registration you submitted has been received by MARE. 
3.) Remove bolded "Submit Your Homestudy" towards bottom of the form.

**Comment by bchiaruttini** [comment]
@n-devr tested in dev and looks good to push. thanks.
