### ISSUE TITLE
Registration Does Not Appear when an event is placed in 'Other Opportunities & Training Tab'

### ISSUE THREAD

**Issue by joesmare** [mareinc/mare#157]
There is an issue with the registration process rendering when a logged-in user opens an event listed in the Other Opportunities & Trainings Tab. We would like for events on this tab to mimic AP registration when the "prevent registration tab" is not selected. 

Additionally, change heading on this tab to "The following are events, trainings or resources of interest offered by MARE and other partner agencies. "

**Comment by autoboxer** [comment]
Registration was explicitly turned off for these events.  Turning registration back on should be trivial.
