### ISSUE TITLE
Splitting inquiries within a region

### ISSUE THREAD

**Issue by bchiaruttini** [mareinc/mare#169]
Configure way for Boston inquiries to be directed to two different MARE staff people. 

MA-DCFCHE and MA-DCFDOR should be a sub-region directed to one worker

MA-DCFROX and MA-DCFHP shoudl be a sub-region directed to a different worker

**Comment by autoboxer** [comment]
this can be solved by creating regions for each of the sub-regions listed above, then assigning a staff contact for each region.  @bchiaruttini, we can probably take care of this one in 30 minutes or so if you want to connect about it.
