### ISSUE TITLE
Source for Web Inquiries

### ISSUE THREAD

**Issue by bchiaruttini** [mareinc/mare#171]
Any inquiry (general/child specific) that are entered through website by web bot should default to MARE web as the source.

**Comment by bchiaruttini** [comment]
can this be done retroactively as well?

**Comment by bchiaruttini** [comment]
@n-devr Is it possible to verify the email of testfamily1@mare.com on the backend for testing purposes. I am having difficulty testing this as both of the test accounts I use (the other one is daveandbridget@gmail which is real email but can't get verified either.)  thanks.

**Comment by n-devr** [comment]
You should be all set to test @bchiaruttini , both accounts are verified and the latest is up in development.  If you ever run into this issue again it's actually a pretty quick fix in the admin ui:

1. Find the Family/SW/Site Visitor you want to verify.
2. Uncheck the `has active database account` checkbox
3. Save the model
4. Re-check the the `has active database account` checkbox
5. Save the model

The `save` hooks will automatically verify the user when an admin manually activates them.  Always happy to take care of it on my end as well if this doesn't seem to be working.

**Comment by bchiaruttini** [comment]
@n-devr great, thanks for that reminder that I can just do manually.  Tested this story and all looks great.  So I think whole batch ready to push to production tonight?

**Comment by n-devr** [comment]
Yep - I'll push in a couple hours 👍
