### ISSUE TITLE
Remove Hyperlink Ability in Open Text Field of Question Email

### ISSUE THREAD

**Issue by communicationsmare** [mareinc/mare#172]
We are experiencing a number of spam attacks through this email access. There is no need for anyone to use a hyperlink at this point of contact. Please disable the hyperlink function.

**Comment by bchiaruttini** [comment]
@joesmare Is this resolved? I don't see a hyperlink currently.

**Comment by joesmare** [comment]
The ability to add a hyperlink to the free-flow text field still appears to be active. Jared, you said that you could restrict hyperlinks in the open text areas of the inquiry emails, correct?

**Comment by bchiaruttini** [comment]
no longer a persistent concern so closing.
