### ISSUE TITLE
Remove "today's date" next to birthdate field in child and family records

### ISSUE THREAD

**Issue by bchiaruttini** [mareinc/mare#184]

**Comment by autoboxer** [comment]
this is an update to the Keystone.js codebase, and while it's not a correct implementation, there's a pull request that attempted to do this already: https://github.com/keystonejs/keystone/pull/4499

**Comment by marcin-lawrowski** [comment]
I created a new pull request that adds the option to hide Today button:
https://github.com/keystonejs/keystone/pull/4869
