### ISSUE TITLE
Improve ability to read all internal notes in a child/family record

### ISSUE THREAD

**Issue by bchiaruttini** [mareinc/mare#198]
Perhaps:
Create next/previous arrows in an internal note which would bring you to the next/previous note that is a part of that child/family's record.

**Comment by autoboxer** [comment]
this isn't supported in the admin UI.  We can discuss other potential ways to make it work.

**Comment by bchiaruttini** [comment]
Shrink ID field, remove SW/Family field headings in order to expand note.
