### ISSUE TITLE
Add additional item under Recruitment Options checkbox in child record

### ISSUE THREAD

**Issue by bchiaruttini** [mareinc/mare#200]
Add two additional checkboxes on this list entitled:

Wendy's Wonderful Kids Caseload East

Wendy's Wonderful Kids Caseload West

*could we run a list of kids with these designations selected?

**Comment by autoboxer** [comment]
@bchiaruttini, each of the current checkboxes displays a date field, and sometimes a video field when checked.  Should the new options have a date field, video field, or both?  In addition, if a child is part of a sibling group, the Wednesday's Child checkbox and related date/video fields will be sibling group specific (and values will propagate to the other siblings).  If the child isn't part of a sibling group, the fields will be specific to only that child.  Do the two new fields get the same treatment, or is it always bound to only a single child?

**Comment by bchiaruttini** [comment]
@autoboxer , they should have a date field with text "date added to caseload".  And yes they should behave in same way as other options, such that if one sibling has the WWK caseload button selected than the other sibling should automatically as well.

**Comment by bchiaruttini** [comment]
tested for both individuals and siblings in development and looks good.
