### ISSUE TITLE
Suppress Location fields and MARE contact fields from Event Form

### ISSUE THREAD

**Issue by communicationsmare** [mareinc/mare#203]
The event form template contains an inaccurate and unnecessary pass-thru of detail. Please disable the bottom location and MARE staff contact info. in the frame.![Event Form Revisions.jpg](https://images.zenhubusercontent.com/585161a1b9dc3c6220238759/3849f0d4-a4f2-4e60-b1ef-3d3427e8d3da)

**Comment by bchiaruttini** [comment]
resolved as part of #207
