### ISSUE TITLE
Create ability for admin to add unregistered event attendees

### ISSUE THREAD

**Issue by bchiaruttini** [mareinc/mare#217]
### as an administrator, I need a way to add unregistered adults and children to an event so that I can control all attendee groups
---

- [x] update the event model to allow preventing admin users from registering through the website
- [x] add a template for admin users to register adults and children
- [x] add a template for admin users to edit adult and child registration
- [x] update service to handle admin user registration- 
- [x] add any necessary flash messages

### original notes from @bchiaruttini:

>Create Register function in the UI so that admin can add an unregistered child, family or adult to an event registration.  
>
>Is there away to unregister an unregistered attendee?

**Comment by autoboxer** [comment]
@bchiaruttini, this can't be done through the admin UI, but per our conversation, I'm assuming having it available on a form on the website will work.  Let me know if that's not the case.  This means logged in admin could go to an event on the website and will see a register button.  They will be able to use this to register unregistered children/adults for the event.  If they have already registered either children or adults, they will see an edit button.  Clicking on that will allow them to edit the list of unregistered children/adults they registered.  It will essentially operate very similarly to family/social worker event registration, with the exception that the admin user won't be asked additional questions, and won't be registering themselves for the event.
