### ISSUE TITLE
Matching functonality

### ISSUE THREAD

**Issue by arek-neptuneweb** [mareinc/mare#220]
Create functions for matching children with families, based on specific criteria. Results will be available on screen as well as downloads.

Tasks:
- [ ] child matching
- [ ] family matching

**Comment by joesmare** [comment]
One consideration that we discussed in our initial briefing. We want to make sure that the matches get captured in the Keystone tracking. Once a match is made through the reporting interface a record will need to be created in Keystone for any matches that are selected as possible matches. This includes both children and family records. One reasonable solution is to allow users to elect matches to be sent to Keystone (child matches to a child record and family matches to a family record). In the 'Relationships' section we can create a field called 'Matching History' and pull over the date and family name (child record) or date and child name (family record). Each line item carried over to Keystone Matching History would allow the staff member to manually further qualify the line item match with selection (radial button choice of) 'Homestudy Sent' or 'Homestudy Not Sent' and a free flow notes section to further qualify the choice. The other marker that will need to carry over will need to be for the person who made the decision about pulling kids from the report to keystone. Additionally we will need to have a delete option in Keystone for any record that we don't need after further consideration.
