### ISSUE TITLE
Save Search Criteria for Known (logged-In) Registered/Homestudied Family

### ISSUE THREAD

**Issue by joesmare** [mareinc/mare#223]
When a registered, homestudied family is logged in, save search criteria at the log-in level so that they don't need to repeat the entry at each waiting child search

**Comment by joesmare** [comment]
The search criteria should save to the Waiting Child Search search screen only. The user should maintain the ability to change the data and have the new limits/selections saved to their search.This info. should not carry over to the related fields in the Family record.

**Comment by bchiaruttini** [comment]
possible, but moderately complicated (few hours).  would likely create a new model and would prepopulate when they return to search again. Could also report out on frequency of searches, etc.

**Comment by bchiaruttini** [comment]
found one issue on this change. When using Anonymous Child in Child matching report, the dropdowns for the fields "other considerations" and "disabilities" are not present.

**Comment by n-devr** [comment]
I'm able to replicate this behavior, just want to make sure we're working on the right story, does this belong to #648 ?

**Comment by bchiaruttini** [comment]
yes you are completely correct and associated with 648.  will update.
