### ISSUE TITLE
Change to drop down in Family Info Preferences

### ISSUE THREAD

**Issue by bchiaruttini** [mareinc/mare#224]
In family record, under Info Preferences, change drop down selections to be Email, Hard Copy, or referred to AUK.

What does this change mean for past records?

**Comment by autoboxer** [comment]
to make the change I'll need to create a script that will update the three existing options (English, Spanish, None) to one of the new values (Email, Hard Copy, Referred to AUK).  Alternately, we could hide the old field to preserve the information and create a new dropdown.  If we want to backfill existing records with one of the values, it will add a little more work.

**Comment by bchiaruttini** [comment]
@autoboxer Please hide the old fields to preserve the information and create a new dropdown with Email, Hard Copy and Referred to AUK as choices. No need to backfill existing records.

**Comment by autoboxer** [comment]
@bchiaruttini, site visitors have the same info packet field.  Should I make the update to the Site Visitor dropdown as well?

**Comment by bchiaruttini** [comment]
@autoboxer Yes please replicate for site visitor as well.

**Comment by bchiaruttini** [comment]
Looks good for creating new records.  However for existing records, you cannot see the past selection of English, Spanish or None.  If I understood your notes on this correctly, I thought it would continue to read Spanish for old records to preserve this info, but we just could not use  those selections moving forward if we were to change or update.  Please see record 42722 as a example

**Comment by autoboxer** [comment]
Update from our call: The old field will be made visible, but not editable.

**Comment by bchiaruttini** [comment]
All looks good, can you please just remove the explanation 
"this is just a reference from when the info packet options were different"
