### ISSUE TITLE
Change to confirmation of inquiry email

### ISSUE THREAD

**Issue by bchiaruttini** [mareinc/mare#239]
Add to the confirmation of inquiry email (general and child specific) the family's workers’ email address and name of agency, if provided.

**Comment by bchiaruttini** [comment]
I attempted to test this but I think emails need to be turned on in order to test fully.

**Comment by bchiaruttini** [comment]
In testing this I also noticed a change in CSC Regional contacts which now displays ALL MARE staff in the drop down options.  Can we change this back to only displaying ACTIVE MARE staff?

**Comment by autoboxer** [comment]
The CSC Regon Contact and Staff Email Contact should only be pulling from active admin.  I need to check all other Relationship Admin fields to see if their filtering as well.

**Comment by bchiaruttini** [comment]
tested email function in development and all good.  Still unresolved is the CSC Region contact and staff email contact pulling from all admin list.

**Comment by autoboxer** [comment]
@bchiaruttini, updating to only select 'active' admin is something I need to look into.  I thought we had examples of it already in the code, but I was mistaken, and couldn't find a quick way to handle this.  I'm creating a new story which will list all the places admin are referenced.
