### ISSUE TITLE
Create a 30-Day Database Back-Up

### ISSUE THREAD

**Issue by joesmare** [mareinc/mare#240]
Create a back-up that extends beyond our current 10-day impression:

-House on AWS S3 Server
-Store 30-rolling days of data
-Allow for restoration of a wider range of data in the event of failure

**Comment by n-devr** [comment]
I've updated the backup plan in mLab and added a new S3 bucket: [mare-backups](https://s3.console.aws.amazon.com/s3/buckets/mare-backups/mongolab/?region=us-east-1&tab=overview).

I ran one on-demand backup to ensure the mLab bot could access our S3 bucket, but we should check in regularly to make sure the backups being run and stored nightly.  We should also check in after a month to ensure that old backups are being removed automatically so we aren't incurring costs for backup data we don't need.

**Comment by joesmare** [comment]
Leaving open until after 30 days to confirm that this is working.

**Comment by joesmare** [comment]
@n-devr if this was implemented on 12/18 then we are by the 30-day mark. Can you check to make sure it is working and close it if it is? TY

**Comment by bchiaruttini** [comment]
@n-devr Can you confirm this is working so we can close out? thanks.

**Comment by n-devr** [comment]
Confirmed - the 30 day rolling back up is working properly 👍
