### ISSUE TITLE
Figure out display of Family's SW info in account.

### ISSUE THREAD

**Issue by bchiaruttini** [mareinc/mare#242]
Currently, when creating a new account, family is prompted to enter their social worker, SW agency and SW contact info.  This information does not make it into the confirmation of account creation email, and only the SW name but not agency or contact info make an imprint in the record.

When the family logs into their account page, they cannot view/edit what they previously entered in these fields.

Based on jared's feedback below, would like to implement the solution suggested:  make the fields hidden, allowing the family to see the values they entered during setup, but clearing the fields once a proper social worker is selected. In their account page, they would see the information they entered if no social worker is selected, and the official information pulled from that social worker's account if one was.  Also need to add the field of SW, SW agency and SW contact info to the confirmation of new account creation, so that MARE staff can update with accurate social worker.

**Comment by autoboxer** [comment]
Our original intent was to have CSCs update the family account with the correct social worker in the system based on the social worker text values sent in the email.  @bchiaruttini, If we have these new fields available on the model, do you think it will encourage CSCs not to update the records with the correct social workers?

One option to mitigate risk is to keep these fields hidden but persist even if a social worker is selected by a CSC, but that presents the problem of staff not being able to easily determine what the family entered during registration.

Another option is to make the fields hidden, allowing the family to see the values they entered during setup, but clearing the fields once a proper social worker is selected.  In their account page, they would see the information they entered if no social worker is selected, and the official information pulled from that social worker's account if one was.

Either way, giving the user the ability to update the social worker means we need to create an email for when they make changes to those fields in their account page.  This is something we might want to discuss at our next meeting.

**Comment by bchiaruttini** [comment]
Of solutions presented above, let's go with:
make the fields hidden, allowing the family to see the values they entered during setup, but clearing the fields once a proper social worker is selected. In their account page, they would see the information they entered if no social worker is selected, and the official information pulled from that social worker's account if one was.

In order for this to happen, the confirmation of account creation email to MARE staff needs to include the social worker, agency and contact info, so that MARE staff can enter manually.

**Comment by joesmare** [comment]
This has been updated in #406 with new details pertaining to the current build. Closing for duplicity.
