### ISSUE TITLE
Make login id non-case sensitive

### ISSUE THREAD

**Issue by bchiaruttini** [mareinc/mare#249]
Several users (mostly SW) having difficulty because they are entering their email with capital letters and unable to log in. Is it possible to remove the condition of case-sensitivity for log-in?

**Comment by autoboxer** [comment]
Note for future development:

The password matching code is part of Keystone.  If we want to handle this outside of a Keystone update, I'd recommend the following:

1. determine how to decrypt the passwords using the bcrypt library
2. write a script to update every user record in the system, decrypting the password, converting it to lowercase, then resaving it to the record
3. update the account code to convert newly submitted passwords to lowercase (handles saving through the website)
4. update all user models with a presave hook to convert all passwords to lowercase (handles saving through the model)
5. update the login functionality to convert the password to lowercase before submitting to log in the user

**Comment by bchiaruttini** [comment]
captured in 338.
