### ISSUE TITLE
Eliminate Accidental Event Attendee/Participant Data Over Save

### ISSUE THREAD

**Issue by joesmare** [mareinc/mare#250]
When working in a loaded event model, making changes and hitting save causes a loss of any data that is in process of loading. Ultimately Jared will work to resolve this issue in a v.4.0 update to Keystone. A proposed interim solution is to create a "spinner" that will replace the save button until all data is loaded to help reduce the chance of an over save.

**Comment by joesmare** [comment]
Jared reported movement at Keystone, when we last spoke, indicating that they were allowing code modifications. We should make this a Keystone priority.

**Comment by joesmare** [comment]
@autoboxer advised that he reached-out to Jed and hasn't heard back. He will attempt to reach another member of the team. He will also use this as an opportunity to introduce @n-devr  to the Keystone team.

**Comment by joesmare** [comment]
@n-devr there have been recent occurances with the "dropped attendees" list being generated through email where there is seemingly no one responsible for the oversave. In the absence of having a holistic solution (such as the spinner to replace the save button as detailed above) there is a sense of urgency to finding the flaw that is causing this issue. In the most recent incident @bchiaruttini reports that multiple lists were generated for the same "dropped children" AND that they were actually not dropped from the event. Here is her advice:
_______________________________________________________
1.)	I got three copies of the same email
2.)	None of these attendees were in fact dropped from the list
3.)	I know for a fact that Anna was in a meeting when these came through.  Could have been Mo, but eliminates one of the usual suspects.

Noah did not have any miraculous solutions to this problem, but we did discuss a few options that he could explore further. 
______________________________________________
I am not privy to what your thoughts were that you discussed with Bridget, but I am pushing this to the top of the list so that you can follow-upon those ideas, should you have time to work before our time together in the office on Weds. Happy to speak as needed.

**Comment by n-devr** [comment]
This issue will still require a fix to be made within the Keystone core project itself.  I haven't dug in to the code yet, but I imagine the change will be difficult and time consuming.  I'm happy to tackle it, but it's not something that I can do in a couple days and will probably take up a large portion of my weekly MARE hours if not more.

**Comment by n-devr** [comment]
I'll look into implementing a document versioning system to prevent users from overwriting each other's changes, which can (hopefully) be done without making a change to the core KeystoneJS codebase.

**Comment by joesmare** [comment]
Document Versioning is completed. I will close this story and re-open a new one with the original goal. @n-devr can we please check with @jared to see if he ever heard anything from Jed about making and loading the update to code to allow for the open part of this story (adding the spinner to prevent over-save). I believe that this version is now open for code revision by the user group, but I also seem to remember that the group may have moved to the next version.
The long and short of it is... @n-devr I know this will be a big project. I just want to know if we develop the code to fix it if we can drop it at Keystone. We can think about the staging and time estimates once we get a definitive answer.
