### ISSUE TITLE
On child reg form, ability to recall earlier submissions to duplicate sibling info

### ISSUE THREAD

**Issue by bchiaruttini** [mareinc/mare#256]
Related to #135 

If worker has submitted a child registration form, when they go to submit another they are given the option to:
1.) Prepopulate fields from an already registered sibling's form. Submission of this new form will result in account creation.  Fields that should automatically prepopulate are:  
Is child to be adopted as part of a sibling group? YES
Recommended Family Constellation
Other Family Constellation Considerations
All RECRUITMENT WORKER INFORMATION
All ADOPTION WORKER INFORMATION

2.) Select an already registered child's form to provide an update to that record.  Submission of this form will result in an email sent.  All fields should be available to update, but is it possible to highlight:
Where does this child presently live?
City of Location
Name of Group Home/Residential
Legal Status
All 4 Needs Text Boxes
All of the Interests, School, Family, etc. Text Boxes

**Comment by bchiaruttini** [comment]
Content for header should read:  PLEASE NOTE: If you do not complete submission of this form, you can return at a later time to restore your work for this particular child. 

The current banner that asks you if you would like to restore should be in red or some bolder font.

**Comment by n-devr** [comment]
@bchiaruttini  the updated banner(s) and the pre-populate a new child registration form from an existing child are implemented in development.  Can you take a look and make sure that everything looks and works as you expect?

For the 'edit an existing child' piece there is a bit more work to get to the desired state.  If I understand correctly, some fields should be highlighted, but any fields that are updated should be put into an email that is sent to the MARE staff.  Please let me know if my understanding is correct!  Also is there an existing mailing list that should receive the email update?

**Comment by bchiaruttini** [comment]
@n-devr Regarding the banners and forms it appears that everything is working as I would expect.  however I am hoping to make instructions clearer as this functionality will be new to users.   Could we add:

If you'd like to Register a new child for MARE services, submit the form below.
If you'd like to update an existing MARE registration, select the child below who was previously registered.
If you'd like to add a sibling to a child who was registered before today, select the sibling below who is already registered.  (And then have drop down for "Populate form for existing child"

For the Green Banner, please change text to read: Please Note
If you are unable to complete this form in one sitting, you can return at a later time to restore your work for this particular child registration from.   You are not able to save work on multiple registrations at the same time.

For the pink banner, please change text to read:  It appears you may have previously started a child registration form that was never submitted.  Do you want to restore the details of this earlier registration? 

(Question for the pink banner....is this only the case if they are in the same browser or is linked to their user account??)

For the edit an existing child, your understanding is correct.  However if complicated to highlight specific fields, we could also just make them available to update, as it appears now.  And same with email, if easier to just have all info go into an email, that is fine too.  The email would go to the staff person who is designated in keystone to receive child registration forms, however should have a clear heading or subject line that identifies it as an update and not a child registration confirmation, as they will look quiet similar in content.  Happy to discuss further on Wed as well.

**Comment by n-devr** [comment]
The instructions and banners have been updated and deployed to development.  The only change I wasn't able to make was to the behavior around updating an existing MARE registration: that still needs to be a link because we actually load a different form with completely separate logic.  I updated the language to match as best I could, but the existing functionality remains in place.

**Question for the pink banner....is this only the case if they are in the same browser or is linked to their user account?**
The pink banner uses LocalStorage to save partial form submissions, so the behavior is tied directly to the browser, not the user's account.

I don't think highlighting specific fields or submitting only the fields that changed via email will be an issue - I'll move forward with that as my target behavior.

@bchiaruttini please take a look at the content changes and let me know if those are all set - I'll move forward with the edit existing child functionality in the meantime.

**Comment by bchiaruttini** [comment]
@n-devr Got it.  Two additional changes:  
1.) When you follow link to update existing child registration, on update page please have heading read CHILD REGISTRATION UPDATE, and remove intro text paragraphs. For the drop down on this page, change from to Retrieve child data, to Update Existing Registration for
2.) On initial child registration page, change text before dropdown that currently reads: Populate form using existing child, to read Select previously registered sibling (if applicable).

**Comment by n-devr** [comment]
@bchiaruttini the additional changes are ready for review in develop.

If you're OK with it I'd like to close out the "recall earlier submissions" portion of work and make a new story to track the "update existing records" portion.  We've completed all of the "recall earlier submissions" work (unless you have any additional requests) and it'll be easier to address the "edit existing" work as its own story.  If you're OK with that I'll go ahead and make the new story and close this one out, just let me know.

**Comment by bchiaruttini** [comment]
@n-devr Got it, so you will push the recall earlier submissions work to production, and keep working on recall earlier submission under a separate story? I reviewed previous changes in dev and all looks good.

**Comment by n-devr** [comment]
You got it @bchiaruttini! I'm hoping to be able to push the latest batch of changes to prod on Wednesday night.  I created a new story for the edit child record functionality (#392) - feel free to add any details I may have missed.
