### ISSUE TITLE
add two additional fields to child registration form 

### ISSUE THREAD

**Issue by bchiaruttini** [mareinc/mare#263]
Add two mandatory checkboxes to child registration form, Y or N

Child has been assigned a secondary worker in the ADLU  (referral will not be active until secondary worker assigned)
Child has had an adoption assessment completed

These fields only need to be in email generated to MARE staff, does not need to make imprint in child's record.

**Comment by n-devr** [comment]
Do we know where on the form these checkboxes should display? @bchiaruttini

**Comment by bchiaruttini** [comment]
@n-devr They can be towards the top of form, ideally between DOB and Languages Spoken, but can be flexible if works better elsewhere.

**Comment by bchiaruttini** [comment]
@n-devr Can we make these two questions mandatory with a Y/N checkbox?

In which case they should be questions:
Has child been assigned a secondary worker in the ADLU?
Has child has an adoption assessment complete?

**Comment by n-devr** [comment]
Yeah we can definitely do that 👍

**Comment by n-devr** [comment]
The form has been updated to reflect the language changes and use required radio buttons.  Here is the relevant excerpt from the email that is generated:
![image](https://user-images.githubusercontent.com/5726612/67534559-aa0fbd00-f69c-11e9-9491-086c6b08c86f.png)

Let me know if anything else needs to be updated @bchiaruttini !

**Comment by bchiaruttini** [comment]
looks perfect @n-devr. Ready to push.
