### ISSUE TITLE
Make relationship fields mandatory in Placement models

### ISSUE THREAD

**Issue by bchiaruttini** [mareinc/mare#283]
In relationship fields, (matches/placements, etc.) do not allow to save without a child and family selected, either registered or unregistered.

**Comment by n-devr** [comment]
Per discussion with Bridget - removing low hanging fruit tag and sending back to the backlog.  This could be accomplished in a pre-save hook but not as simple as adding a property to the model.

**Comment by bchiaruttini** [comment]
@n-devr I took a look at this one, and actually think making the child field mandatory solves the problem, without having to make the family fields mandatory as these are more complicated.  So fine to keep as is, and apply same logic that is currently in placements to matches, disruptions, legalizations, and WFC.  The only change I would like to see is that when you select an unregistered child, the first and last name should be mandatory, but not the status.
