### ISSUE TITLE
Update Child Matching Model on Reporting System

### ISSUE THREAD

**Issue by joesmare** [mareinc/mare#286]
Using the slack image as model for field addition, make changes to the Child Matching model on the reporting suite. Please work on http://development.adoptions.io. 
In addition to the field additions, please assess the following changes:

1. Let us know how much work it will be to change the child's age from the lower limit to any to a revised any to upper limit
2. Please assess the ability to bring the user to the area where search data is presented vs. at the top of the web page

**Comment by n-devr** [comment]
Adding diagram of changes for easy access.

![Child Matching Template Changes](https://user-images.githubusercontent.com/5726612/62885915-056e1800-bd08-11e9-9c56-7ead8b6bbea9.jpg)

**Comment by joesmare** [comment]
Based upon our recent call we are parsing this into multiple parts:

1. Add fields in child record
2. Change returned data fields
3. Work through upper and lower limits for age and various needs (both child and family)

Once completed and tested we will push this to production.
