### ISSUE TITLE
Inquiry Report

### ISSUE THREAD

**Issue by joesmare** [mareinc/mare#307]
Please see the attached file. Inquiry reporting details are presented within.[https://app.zenhub.com/files/124335727/e6012754-25f5-4cde-9f7c-ec001caba49b/download](https://app.zenhub.com/files/124335727/e6012754-25f5-4cde-9f7c-ec001caba49b/download)

**Comment by n-devr** [comment]
Do we have an icon for the Inquiry Report sidebar button @joesmare ?

**Comment by joesmare** [comment]
We didn't define anything yet. I was thinking of using overlapping talk bubbles indicating two way conversation. I've attached a sample. Jeremy or I can transform it into whatever format you need. Thinking ahead I thought we could use a house for placements, indicating that the child has a new permanent home. Thoughts?
![Talk Bubbles](https://user-images.githubusercontent.com/41170314/65344782-9d341100-dba6-11e9-825d-c4c4e3aded03.png)

**Comment by n-devr** [comment]
I like the talk bubbles and the house idea for placements - simple and topical.  Based on the icons that are currently being used for child/family matching, it looks like we would want to use a .PNG with a transparent background that's about 113 pixels wide and 90 pixels tall.

**Comment by joesmare** [comment]
I'll have @jeremysMARE produce and send over early next week.

**Comment by joesmare** [comment]
MODIFICATIONS to discuss:

Calendar:
-Can we look for a calendar that allows you to type in the date or modify the current calendar to do so?
-Can we add a button for past fiscal years (Jul 1 -Jun 30)? A minimum of the past two FY

EXPORT DATA
-Add column for sources (our source and user source 'how did you hear about MARE?' data)
-When MARE source isn't listed use free flow text source from user
-Remove spaces in Excel report to allow for meaningful sorting capabilities
PDF EXPORT
-Mirror Excel export fields

**CHILD FIELD
-Can we add a search field for a specific child? This can be accomplished in Keystone, but this report could also be a place to run a child specific report

**Comment by n-devr** [comment]
Remaining tasks per discussion with Joe:
- [ ] Add separate columns for `Source`, `Additional Source(s)`, `Intake Source`
- [ ] Comma separate children and disabilities
- [ ] Add buttons to pre-fill previous fiscal years in date range inputs
- [ ] Add search input field for Children

**Comment by joesmare** [comment]
Hello @n-devr . I had Bridget review the updates and she had a few suggested modifications:

1. Please remove the column in the on-screen return labeled 'Inquiry Method' and replace instead with the inquiry date.  You may leave inquiry method on export.

2. Can you add legal status to export only?

3. Child social worker region is missing from the export version.

2. The left rail that houses the report buttons is taking-up space that could be used for the on-screen return results. I would like to discuss the following two options:
     -After you make a report selection the left rail minimizes to the left with a tab to reopen, thereby giving us an extra row or two of space to present the data
     -If the first option is too difficult, can we reduce the width of the left rail? There is a lot of white space in the buttons. Perhaps reduce the button size and rail?

**Comment by n-devr** [comment]
OK, thanks @joesmare - 1 through 3 are fairly simple changes that I can tackle next week.  Just for the record, I didn't include SW Region in the exported versions because it wasn't included in the requirements doc.

For #4 - I totally agree that the on-screen results could use more room and are sometimes tough to read, especially when there are a lot of results.  Adjusting the left rail could help reduce the clutter a little bit, but it's a band-aid fix for the larger problem of trying to cram so many results into a page without proper structure.  I strongly recommend that we implement some sort of grid component that can support column resizing, horizontal scrolling, and content formatting at the very least.  If we're going to spend time making the results more readable, we should implement a solution that will address the root cause of the problem rather than addressing the symptoms.  A proper grid will also future-proof the dashboard against views with more data, and allow us to add more columns to existing views without being concerned about compromising legibility.

**Comment by joesmare** [comment]
No worries about the SW piece. Just an oversight that I wanted to note. You are following the direction that is provided. These changes are an evolution of the reporting as we review what we initially staged.

Let’s discuss #4. I like your proposal. It makes more sense to have expandable space.

We can speak on Monday, as planned.

Joseph Sandagato
Director of Communications and Public Relations
Massachusetts Adoption Resource Exchange
[MARE]
We find adoptive homes for children and teens in foster care.
19 Needham Street, Suite 206 | Newton, MA 02461
Telephone: (617) 964-6273 ext. 115
Website<http://www.mareinc.org> | Facebook<https://www.facebook.com/massadopt/> | Twitter<https://twitter.com/massadopt> | Instagram<https://www.instagram.com/massadopt/>

**Comment by joesmare** [comment]
One additional bit of feedback that I've received is with regard to separating the lines of on-screen returns with an alternating color scheme (white/gray or similar) to help with readability. Since we are reworking the section it makes sense to discuss this at the same time.

**Comment by joesmare** [comment]
RE: #4 Let's do the following (pending your investigation of ability to do so):

1. At home screen present left rail until an action is taken (i.e. click on report). Upon that action have left side rail slide and hide to the left with a tab to retrieve it.
2. When presenting on-screen report data, alternate colors (zebra stripe) the return for ease of reading
3. Look for a solution to transition the on-screen return from a table to a grid which will also allow for expandable returns (i.e. a bar to navigate to the right).

This encompasses all of the current demands. I believe that you are breaking this out to a separate story, but I didn't see it staged.

**Comment by n-devr** [comment]
I created #343 to cover the work to be done on the left rail.  My understanding was that you were collecting additional requirements for the grid from the wider team and creating a story to track that effort.
