### ISSUE TITLE
On Family Matching Add Family Status (view only) and auto check "active" under child status

### ISSUE THREAD

**Issue by joesmare** [mareinc/mare#319]

**Comment by n-devr** [comment]
This is all set, I just need two pieces of content:

1. When the family is not registered (`registered with MARE = false` in the Admin UI), what text should we display?

2. When the family is registered but no Status has been chosen, what text should we display?

@joesmare

**Comment by joesmare** [comment]
I assume you are referring to the preview pane on the Family Matching screen? If so can we make "Not Registered with MARE" and "Set Family Status" the responses. That will suggest to the user that they need to update the record. Does that make sense?

**Comment by n-devr** [comment]
Yep, makes sense to me! I'll update the content and push to develop shortly.  Ready for review whenever's clever 👍
