### ISSUE TITLE
Take siblings into account when setting needs range fields on child matching dashboard

### ISSUE THREAD

**Issue by n-devr** [mareinc/mare#331]
If a child has siblings, use the highest level of needs to set the default value of the needs range fields.  For example, if the child you are matching against has mild emotional needs, but they have a sibling with moderate emotional needs, the emotional needs range should default the lower bound to moderate instead of mild.

**Comment by joesmare** [comment]
@Noah this seems consistent with our discussion. We do need to further assure that when defined child matching needs are compared to defined family parameters that any families who have the child need level defined, as part of their range, are returned. Seems to be working fine now. Just want to make sure that by changes made don’t impact that aspect. TY
