### ISSUE TITLE
Better Error Messaging

### ISSUE THREAD

**Issue by joesmare** [mareinc/mare#338]
- [ ] Remove case-sensitivity from email field validation.  Users are currently prevented from submitting the login form if there are any capital letters in their email address, which is causing issues for Social Workers in particular.
- [ ] Update the `Forgot?` prompt on the login form to `Forgot Password?` to increase discoverability.
- [ ] Disable the Submit button after the first click so that users cannot generate errors by clicking the submit button multiple times.
- [ ] Generate a more accurate error message when the user has entered an incorrect email or password to allow them to self-diagnose the issue and prevent unnecessary emails chains.
- [ ] Update all login error messages to prompt users to email `web@mareinc.org` instead of any other address.
- [ ] Display a success flash message when a user logs in.
- [ ] Remove the success message automatically after 3 seconds.

**Comment by joesmare** [comment]
This looks fine @n-devr; the specific message withstanding. If you can generate a message to intuitively  indicate the error (user ID/password or both). That would be most beneficial. Forgotten user ID or password? Direct to web@mareinc.org as indicated.

**Comment by n-devr** [comment]
Can do, @joesmare .  I do want to call out that indicating which part of the login failed (username/pass) goes against security best practices as it allows potential bad actors to confirm that a username is in use.  That being said, it will help less technical users self-diagnose their login issues, so there is definitely a trade-off.  Let me know which way you want to go.

Also, do we want to direct people to email if they forgot their password or should we try to have them go through the automated password reset flow?

**Comment by joesmare** [comment]
You're fine with saying either user name or password for maximum security (although there really isn't any real security risk, but we do get a ton of spam masking as intent...so why make it easier). 

We can direct them first to reset password, but I'd like to make it clear that they can get support from web@mareinc.org if they forgot their user name, so maybe something in-between:

"...If you've forgotten your password, you may reset it <<here>>. If you have forgotten your user name or need additional assistance please contact web@mareinc.org"

Thoughts?

**Comment by n-devr** [comment]
Makes sense to me.  I do think we should try to shorten the content as much as possible.

Maybe something like:
> Forgot your password? Reset it here.
> Forgot your username or need additional assistance? Contact web@mareinc.org

**Comment by joesmare** [comment]
Sounds good.
Joseph Sandagato
Director of Communications and Public Relations
Massachusetts Adoption Resource Exchange
MARE
We find adoptive homes for children and teens in foster care.
19 Needham Street, Suite 206 | Newton, MA 02461
Telephone: (617) 964-6273 ext.115
________________________________

**Comment by bchiaruttini** [comment]
discussed including validating email errors in this story
