### ISSUE TITLE
Small change to Child Reg Form

### ISSUE THREAD

**Issue by bchiaruttini** [mareinc/mare#350]
On the Child reg form, under section titled Other Family Constellation Considerations, change check box for "no pets", to read "CANNOT be in home with pets" and change order so that this is the last checkbox in this section.

**Comment by n-devr** [comment]
@bchiaruttini I made an update to the `Other Family Constellation Considerations` model to allow you to control the ordering in Keystone.  I will demo for you when we meet, I'm hoping it will allow you to make changes like these in the future without the need for any code updates.

**Comment by bchiaruttini** [comment]
we reviewed how to make this change and I made in production, so story can be closed.
