### ISSUE TITLE
Add "all" button to date range options for Inquiry report

### ISSUE THREAD

**Issue by bchiaruttini** [mareinc/mare#355]
placed somewhere where you will proactively have to select to minimize unnecessary crashing.

**Comment by n-devr** [comment]
I simulated this functionality by setting the 'from' date to 1800 and not entering any other criteria. The server a few times, but I was able to get it working intermittently by increasing the memory available for the server.  On the times the server was able to handle the request, the browser itself crashed when trying to render all of the inquiries in the grid.  

Based on this behavior I recommend that we forgo this functionality and potentially look into creating an upper limit for the number of records returned.  I don't think this scenario is common enough that we absolutely have to limit the number of results, and the production server itself should be able to handle the requests, but if we notice crashes as people are using the dashboard we might need to implement a limit.

@bchiaruttini are you OK with leaving the 'All' button off of the dashboard?

**Comment by bchiaruttini** [comment]
@n-devr In thinking more about this, there is really only one test case in which the ALL functionality is needed.  Is it possible in the inquiry report, that when a specific child is selected, then the ALL button appears along side the FY buttons?  this would allow us the info I am looking for, without ever returning more than 100 or so inquiry records.

**Comment by n-devr** [comment]
The "All" button is now implemented and deployed to develop - ready for review whenever you have a moment.

**Comment by bchiaruttini** [comment]
@n-devr, tested and all looks good.  I did however find one other area where this functionality of the ALL button would be very helpful.  In the placement report, if a source is selected (whether placement, disruption, etc.), the ALL option should appear. I am sorry I did not identify this earlier so I can open a new story if preferable.  thanks.

**Comment by n-devr** [comment]
No worries @bchiaruttini - we can track it as part of this story.  I'll just add a task for it here:

- [ ] Add an ALL button in placements reports, visible when a source is selected

**Comment by n-devr** [comment]
Actually @bchiaruttini I do have a question as I'm looking into a fix for this.  You mentioned a "source" being selected, but you listed "placement types" as examples - which dropdown selection should the ALL button respond to?

**Comment by bchiaruttini** [comment]
@n-devr In placement report, the field that it should cue off of is "source" and/or "additional source" to display the ALL option.  And perhaps this is irrelevant, but I was just attempting to highlight that the behavior should be the same whether the sub-type of placement, match, disruption or legalization is selected.

**Comment by n-devr** [comment]
Got it, thanks for clarifying.  I read those as different options that might be in the Source field so I just wanted to make sure I was listening for changes on the right dropdown.  If I understand correctly, the ALL button should appear if any options are selected in either the "source" or "additional source" dropdowns.

**Comment by bchiaruttini** [comment]
@n-devr  yes correct, thanks!

**Comment by n-devr** [comment]
@bchiaruttini the ALL button is now working on the placement report search form and is ready for testing on develop.

**Comment by bchiaruttini** [comment]
@n-devr  tested and looks good to push to production in next batch. thanks.
