### ISSUE TITLE
Rearrange order of columns in Inquiry/Placement reports

### ISSUE THREAD

**Issue by bchiaruttini** [mareinc/mare#358]
In inquiry report, order of columns should be:
Inquiry icon linking to inquiry record
Inquiry Date
Inquiry Type
Child First Name 
Child Last Name 
Child Reg #
Child SW Reg
Contact #1
Contact #2
Family Reg #

In placement report, visible fields in the return should be (in order):
Placement Icon linking to placement record
Placement Date
Placement Notes
Child First Name (reg or unregistered)
Child Second Name (reg or unregistered)
Child Reg #
Siblings to be placed with
Contact #1 (reg or unregistered)
Contact #2 (reg or unregistered)
Family Reg #
Source
Additional Source

In placement, fields that should be column visibility selections and export should include:
Race 
Gender
Legal Status
Adoption worker
Adoption Worker Agency
Adoption Worker Region
Registration Date
Days before placement (difference between placement and registration dates, may not be possible but have excel formula if needed)
Age at placement
Levels of Need
Family Agency
Family Region
Family Constellation
Contact #1 Race
Contact # 2 Race
Registered with MARE box selected Y/N

**Comment by bchiaruttini** [comment]
@n-devr If we can fit in all nine (plus icon) columns in the full display then we would not need any addition in the column visibility toggle. If for some reason they don't all fit, I can re-prioritize.

**Comment by n-devr** [comment]
@bchiaruttini the amount of columns we can fit will come down to the size of the device that a user is viewing the report on.  we can keep them all visible by default for now, then if we want to hide a few of them by default in the future that's an easy change to make.

**Comment by n-devr** [comment]
@bchiaruttini how should the data be formatted in the 'Levels of Need' column?  If I'm understanding the requirement correctly that would be a lot of data to try to display in a single column. Should each need have its own column?

**Comment by bchiaruttini** [comment]
Yes you are correct.  There should be a column each for physical, emotional, intellectual and social needs, displaying the level selected (none, moderate, etc.)

**Comment by n-devr** [comment]
@bchiaruttini I've added all of the additional (hidden) columns to the Placement Report grid.  Please take a look and let me know if the data is coming through as expected.  If it looks good I will add all of those columns to the export grids (PDF and Excel).

**Comment by n-devr** [comment]
I've added all of the columns to the PDF and Excel export views as well.  The Excel export looks good, but the PDF export is not able to display all of the columns because it is limited by the width of the printable page (11").  

Please let me know how you'd like to proceed for that case.  I don't think there's much we can do to fit additional columns into the display, but we could display a different subset of columns for the PDF export only.

**Comment by bchiaruttini** [comment]
@n-devr Sorry about my delay in reviewing these, but looking good.   I am comfortable with the PDF export not being able to display all fields as long as the XLS export does. 

Re: Inquiry Report. I apologize as I am now better understanding your comment above about wanting all hidden fields available on the column visibility dropdown. To be consistent with how the Placement Report functions, please add all fields that are available in the export to be options on the Column Visibility Dropdown. 

Regarding placement report: For default visible fields, please swap out Notes field for Placement Source field.  Additionally, in my browser in cases where your search returns only a small number of records, the Column Visibility list was longer than the return list, and thus I could not access all fields (see screen shot attached).  Is there a way to still be able to scroll below the return list?

![image](https://user-images.githubusercontent.com/37884165/67420129-00e19d80-f59c-11e9-942a-d0648b454278.png)

And this final one is not a big deal at all, but I noticed that if you hit the PDF export, when you return to the list it goes back to the default visible fields, and you lose any customization you had selected. Is there an easy way to preserve the customization?  I can live without this one unless its a simple fix. 

And just want to say that the ability to display the age of child at placement and the number of days before placement is a HUGE enhancement so grateful for your ability to figure this out.

**Comment by n-devr** [comment]
Really glad to hear the age at placement and days before placement are improving the experience!

I will try to capture your feedback as a few additional tasks that I will work on before closing this out:

- [ ] Add hidden columns to visibility toggle for Inquiry report
- [ ] Swap notes and placement source columns as default visible on Placement report
- [ ] See if we can limit the size of the column visibility toggle menu to show all columns on smaller screens (this one might be tough but I think I can do something to make it work)

Saving the state of the grid when navigating away from the page would be really time-consuming to  implement.  A simpler solution would be to just open the PDF in a new page.  You can right click and open link in new page or click the link with your middle mouse button.  I could also update the code to open the PDF in a new page by default.  

Please let me know if you'd like me to add that task to the list and that the list captures your requests @bchiaruttini .

**Comment by bchiaruttini** [comment]
@n-devr Yes that captures it all, however just want to make sure I explained #3 (length of column visibility toggle) correctly. It isn't the size of the screen that impacts it, but the size of the return list. If there are 100 records returned, than you can keep scrolling down on the visibility toggle.  If there are only 8 returns, you can't scroll down far enough to see the whole visibility toggle list. 

And for the PDF export, please update code to automatically open PDF in new window.

**Comment by n-devr** [comment]
Hey @bchiaruttini I've made all of the changes we discussed and deployed them to develop, please take a look when you have a moment.  If we're all set I will deploy to prod over the weekend and we can close out Inquiries/Placements.

**Comment by bchiaruttini** [comment]
@n-devr Thanks, everything looks great on inquiry and placement report, so let's push to production and call this a wrap.  @joesmare
