### ISSUE TITLE
Media Features Report

### ISSUE THREAD

**Issue by joesmare** [mareinc/mare#362]
The media feature report will be used to look at specific media driven responses at the child record level. This crosses between 'child record' and 'media features' silos

[https://app.zenhub.com/files/124335727/7e235499-e007-4ac5-81da-324f34664394/download](https://app.zenhub.com/files/124335727/7e235499-e007-4ac5-81da-324f34664394/download)

**Comment by n-devr** [comment]
Add Inquiry-related columns:
- [ ] Monthly average of inquiries over child's lifetime before media feature
- [ ] Number of inquiries the month after media feature
- [ ] Monthly average of inquiries over child's lifetime after media feature
- [ ] Has child been placed? If so, display date

**Comment by joesmare** [comment]
@noah the team has reviewed the work. Thank you for the heads-up. I know that the exports aren't built yet. We do have the following comments about the current build:
•	We still need columns for "# of inquiries in publishing month" and "average rate of inquiry after media feature"
•      Change the hyperlink symbol at the left to display reg number in the columns

**Comment by n-devr** [comment]
@joesmare thanks for reviewing, I'm working through the math of the remaining two inquiry columns now.  I'll add the reg number instead of the icons as a task.

**Comment by n-devr** [comment]
@joesmare the additional columns are in place and ready for review as well. I've done a bunch of smoke testing myself, but the date math is very complex so please take a few examples and verify the report against the data in the admin UI to ensure the numbers represent the data you expect to see.

**Comment by joesmare** [comment]
@n-devr  the report seems to be functioning well. The team reviewed the final product. Let's hold this until the next report is ready and push them at the same time. In the meantime @jeremysMARE  please  lay a second set of eyes on the output and specifically help me to validate the math that produces the pre, during and post media inquiry rates.

**Comment by n-devr** [comment]
@joesmare the Excel and PDF export functionality is now complete and ready for review in development.  Those were the last tasks on my radar for this story - please let me know if there's anything else that needs to be done before we call this story complete.

One thing to note is that we don't have a unique icon for this report in the sidebar, so if that's something you want to implement we'll need an icon asset to use.

**Comment by n-devr** [comment]
Per review with @bchiaruttini and @jeremysMARE :
- [ ] Update the last column of the report to display the monthly average of inquiries for 6 months from the date of the media feature, or today's date if 6 months have not yet passed.
