### ISSUE TITLE
Child Listing Report

### ISSUE THREAD

**Issue by joesmare** [mareinc/mare#363]
The child listing report contains a large number of dimensions upon which a search can be executed. It is all driven by 'child record', but the sorts and variables are complex. We can discuss further prior to the build.[https://app.zenhub.com/files/124335727/3aa2d90a-59b6-41cb-9618-154eb561642d/download](https://app.zenhub.com/files/124335727/3aa2d90a-59b6-41cb-9618-154eb561642d/download)

**Comment by bchiaruttini** [comment]
@n-devr I took a closer look at the Child Listing Report. I continue to wonder if it might be simpler to make it a build off of the existing Child Matching Report, although don't feel strongly about this.  

Ideally the fields that should be searchable on this report are:
Registration Date (with FY option)
Adoption Worker Region (multi-select)
Adoption Worker Agency (multi-select)
Adoption Worker Name (multi-select)
Recruitment Worker Region (multi-select)
Recruitment Worker Agency (multi-select)
Recruitment Worker Name (multi-select)
Race (multi-select)
Gender (multi-select)
Current Age (Range)
Placement Setting (multi-select)
Siblings to be Placed with (Y or N)
Number of Siblings to be placed with (is this possible, if not could just see names of sibs in the return)
Levels of Needs (Physical, Intellectual, etc.) Multi-select for each category and should be inclusive (i.e. kids who have EITHER moderate physical and intellectual needs, not necessarily both.)
Date Added to Web (date range, with FY option)
Placement Status (multi-select)
Legal Status (multi-select)
Recruitment Options? (would be multi-select from list of Recruitment Options, need to explore further...)
Professional Photo? (need to explore further...) 
Professional Video (need to explore further...)

Fields that can be visible in order of viewable return:
Name
Registration Number
Gender
Race
Legal Status
Current Age
Adoption Worker Region
Adoption Worker Name
Siblings to be Placed With
Placement Status

All of the rest of the fields would be selectable to return in full excel report, including Age at Registration, and Days Waiting (Today's date minus registration date), which would not be searchable.

Can discuss further!

**Comment by n-devr** [comment]
Breaking the above requirements down into a task list so it's easier for me to keep track of what's complete/todo:

### Search Fields
- [ ] Registration Date (from/to date range inputs)
- [ ] Registration Date (fiscal year buttons)
- [ ] Date Added to Web (from/to date range inputs)
- [ ] Date Added to Web (fiscal year buttons)
- [ ] Adoption Worker Region (multi-select)
- [ ] Adoption Worker Agency (multi-select)
- [ ] Adoption Worker Name (multi-select)
- [ ] Recruitment Worker Region (multi-select)
- [ ] Recruitment Worker Agency (multi-select)
- [ ] Recruitment Worker Name (multi-select)
- [ ] Race (multi-select)
- [ ] Gender (multi-select)
- [ ] Current Age (from/to number range)
- [ ] Placement Status (multi-select)
- [ ] Legal Status (multi-select)
- [ ] Siblings to be Placed with (checkbox)

### Report Columns
- [ ] Name
- [ ] Registration Number
- [ ] Gender
- [ ] Race
- [ ] Legal Status
- [ ] Current Age
- [ ] Adoption Worker Region
- [ ] Adoption Worker Name
- [ ] Siblings to be Placed With
- [ ] Placement Status

### Questions/TBD
 - Number of Siblings to be placed with (is this possible, if not could just see names of sibs in the return)
- Levels of Needs (Physical, Intellectual, etc.) Multi-select for each category and should be inclusive (i.e. kids who have EITHER moderate physical and intellectual needs, not necessarily both.)
- Placement Setting (multi-select)
- Recruitment Options? (would be multi-select from list of Recruitment Options, need to explore further...)
 - Professional Photo? (need to explore further...)
 - Professional Video (need to explore further...)
- All of the rest of the fields would be selectable to return in full excel report, including Age at Registration, and Days Waiting (Today's date minus registration date), which would not be searchable.

**Comment by n-devr** [comment]
Additional items per discussion with Bridget:
- [ ] Update default date ranges to be 1 year from the current date
- [ ] Update status labels to use correct terminology

**Comment by n-devr** [comment]
@bchiaruttini the PDF and Excel exports are now implemented and deployed in development

**Comment by bchiaruttini** [comment]
@n-devr @jeremysMARE  Here is some feedback from our review of existing child listing report.  Please review and we can discuss any that need clarity tomorrow.  Thanks!
1. Have default for “Date Added to Web” be none
2. Offer "Clear” option for Date Ranges (maybe part of new calendaring option we’ve discussed)
3. Under Additional Options, add the following (which link to Recruitment Options in Child Record....Don’t necessarily need to be in column visibility?)
professional photo
video snapshot
Adoptuskids website
Wednesday's Child
Wendy's Wonderful Kids Caseload East
Wendy's Wonderful Kids Caseload West
coalition meeting
matching event

4. Add searchable field (either in main area or additional options) for all kids who have “Activate child profile on web to group selected” checked.

5. In XL export (and column visibility) add:
-the names of the siblings to be placed with
-date added to web
-date of registration

6. Is it possible to track display image as output in column visibility and XL (this would link to display image in child’s record, goal of this is to see how many active children are missing profile photos and I believe this is the only way we could get at that) Maybe under Additional Options

7. Reset button at bottom does not appear to be working

**Comment by n-devr** [comment]
All feedback is implemented and ready for review in `dev`

**Comment by bchiaruttini** [comment]
So upon additional testing, the Date Added to Web continues to cause a problem. Essentially, the _date added to web_ appears to be wiped clean from the Child Record when the __activate child profile on website to group selected_ is unchecked, which happens automatically when the child's status is anything but Active. So this means that even by broadening the date range of date added to web to 1/1/1900, it is only returning kids who are active, because those are the only kids for who the date is accessible.   Thus making it impossible to ever see any list of kids with statuses other than active.

So...options as I seem them are to: 1.) see if there is a way to still query the date added to the web, even when the child is not visible on the web. This would be ideal, as the whole intention of adding this field to the report is to be able to see how many kids we profiled in a range of time to capture the work we've done even if not currently active. If not possible, 2.) remove this field all together so it doesn't mess up returns. 

I think this is the primary issue, although the returns for many searches seemed innacurate, but tough to fully test without addressing the Date Added to Web issue first. 

And finally, a small one but can you hyperlink the child's registration number in the return to their keystone record? This is the case in other reports.  

Thanks - happy to provide more details or chat on Monday as needed.

**Comment by n-devr** [comment]
Thanks for the detailed writeup @bchiaruttini - I looked into querying by `date added to web` even when `activate child profile on website to group selected` is unchecked in the child record, but unfortunately it looks like the `date added to web` field gets cleared out whenever a child's status changes to anything other than `active`.  Unfortunately that means I option 2 is our only option to allow non `active` children to be included in the results.

I'll remove those fields and update the registration number to behave as a link to the child record as requested, then hopefully we can get to the bottom of any inaccurate or undesired behavior with the search results.

**Comment by n-devr** [comment]
All updates are in and deployed to dev, let me know if that fixed the accuracy of the results or if we still have some fine tuning to do.

**Comment by bchiaruttini** [comment]
@n-devr updates look good, and seems to have resolved other accuracy issues. (I will add a separate story about finding a way to be able to track kids added to web, as this remains a goal but we can tackle separately.)
But regrettably two additional things:
1.) Under additional options, could you also add "Weekend Family Connections" as an option. sorry that I missed this the first time around but should be on the list.  
2.) In my testing I noticed that if the child is part of a sibling group, then in their record there is a different field for "Wendy's Wonderful Kids Caseload East for sibling group" I honestly don't recall why Jared needed to differentiate this one versus the others, but it does not appear that the query is returning kids who have it checked for a sibling group, when you search for Wendys  Wonderful Kids Caseload East.  Ideally, the checkbox in the child listing report would return both singles and siblings that are on the caseload, but I guess if this is not possible it would mean adding two new checkboxes to the additional options list (WWK Caseload East for Sib and WWK Caseload West for Sib)
