### ISSUE TITLE
Migrate MARE App & database Records (Old MARE Database) to AWS with local access (Bridget/Lisa desktop)

### ISSUE THREAD

**Issue by joesmare** [mareinc/mare#366]
Per the conversation with Brian Huyser, @autoboxer will set-up the environment in AWS to support the migration of the "old MARE Database" to a MARE-owned AWS cloud account. Jared has specific notes from Brian about the tasks to be completed and Brian will review and support Jared in the move. High-level details include:

1. Remove MARE App shortcut path (currently on physical server) on Bridget and Lisa's desktops and replace with full MARE App at desktop-level
2. Set-up AWS to receive DB (to run on SQL server), small IIS app (as the handler), and related security & other tasks
3. Connect the two desktops to the new AWS file location to allow for viewing of the files (i.e. full database function)

*NOTE: no changes should be made to the data/there will be no back-up of these files. While not restricted access, this should be considered "view only" by users once the transition is completed.

@autoboxer please add whatever notes you's like to support this project.

TIMELINE: Anticipated completion by 11/1 (please advise if extension is required).

**Comment by autoboxer** [comment]
Note from the call with Brian:

3 components:
client application - windows - desktop executable
database - SQL server
IIS - website

communication path: client app -> IIS handler -> database

server uses .NET 2.0

need SQL Server Web Edition

AWS security group, we need to open up port 80 and 3389 (for RDP)  eventually I can lock the RDP one down to specific IP address if I want.

go with the latest windows OS 2019 with SQL server 2016 web edition, or for compatibility 2008r2

Brian will need admin access to start

when I provision the windows server, there’s a root size.  Brian recommends EBS with general purpose SSD default sizes are small, he’d recommend 100Gig to be safe and I have a decision if I want the DB to be on the system drive or on another, but for this on the system drive is fine.

**Comment by joesmare** [comment]
There is a copy of the MARE App access point installed on each of Bridget and Lisa's computers which with need to have the new file path to AWS defined as a final step to this process. This replaces the "shortcut" to the MARE App that resides on the physical server.
