### ISSUE TITLE
Add Weekend Family Connections to Website

### ISSUE THREAD

**Issue by joesmare** [mareinc/mare#382]
@jeremysMARE Jeremy will design/share the graphics and gather the written content to add a page to the MARE website entitled "Weekend Family Connections" in cooperation with @n-devr.

The page should be under the main tab "Ways to Help". We should include program details, graphic images and reference to Lindsey as the staff member contact (with contact info.).

**Comment by joesmare** [comment]
Update from meeting:

**ETA for completion**: Final drop before or by 12/18

**Location**: Ways to Help tab over Experienced Families

Jeremy to stage a preview/draft on Development for Lisa/Bridget/Lindsey to review

**Content**:
Lisa to provide @jeremysMARE with brochure content to be applied to web page
Lisa to provide @jeremysMARE with external, blind page, content (family-possible SW/other in future)

@jeremy to use imagery and final brochure content to stage preview. Lindsey to provide content for her bio/program goals block

**Related**:
Also... @jeremysMARE to get content for program description to be added under 'Our Services' labeled as "Weekend Family Connections" and located under 'Family Services'

@noah will work with @jeremysMARE to complete directory work and assure that the final build is complaint with wed/database code standards

**Comment by joesmare** [comment]
@n-devr , @jeremysMARE  is just finishing-up the draft of the page. He will make a note here when it is ready for you to review the code and create the directory.

**Comment by jeremysMARE** [comment]
@joesmare Lisa and Lindsey have reviewed and approved the WFC page. The current draft can be viewed here: https://www.mareinc.org/page/weekend-family-connections

@n-devr Let me know if you need anything from me to proceed.

**Comment by n-devr** [comment]
@joesmare the new Weekend Family Connections page has been added to the website nav - the update is available for review in `development`

Is there any additional work required as part of this story?  I am currently working on the back end changes and will continue unless there's anything else on the front end I need to take care of.
