### ISSUE TITLE
Update registered child's record

### ISSUE THREAD

**Issue by n-devr** [mareinc/mare#392]
Select an already registered child's form to provide an update to that record. Submission of this form will result in an email sent. All fields should be available to update, but is it possible to highlight:
Where does this child presently live?
City of Location
Name of Group Home/Residential
Legal Status
All 4 Needs Text Boxes
All of the Interests, School, Family, etc. Text Boxes

**Comment by bchiaruttini** [comment]
email generated should be sent to staff contact for Child Registration Form

**Comment by n-devr** [comment]
Additional tasks per conversation with @bchiaruttini :

 - [ ] Update link in navbar to "Register/Update a Child"
 - [ ] Update form submit button copy to "Share Updates with MARE Staff"

**Comment by n-devr** [comment]
I'm working on building out the email notification functionality and I have a couple questions:

1. Child registration emails are sent to the staff on the email list `social worker child registration`.  Should I send the edit child registration emails to the same list, or do we need a new one?
2. Is there any other content that needs to be added to the email template?  My plan is to just copy the new social worker child registration template and update the language to describe the `edit` action.

**Comment by bchiaruttini** [comment]
@n-devr, no there is no additional information needed.  The priority is to make it clear it is an update (versus new registration) in any heading, title, etc. so that it is easily identifiable.  And it should be sent to the same staff contact as social worker child registration forms. thanks.

**Comment by n-devr** [comment]
@bchiaruttini the update record form and email functionality is ready for testing in development.  I created a temporary staff email target for testing purposes, so any update requests will be sent to your MARE email address so you can review the emails as well.  Once we are satisfied with the flow I will set the email target to the `social worker child registration` staff contact before we deploy to production.

This ended up being quite a complex task that required a lot of special-cases and workarounds, so I expect that there may be some additional adjustments we need to make before it's ready to be released.  Please let me know if you see any issues during your testing!

**Comment by bchiaruttini** [comment]
@n-devr I tested this out and let's review this morning.

**Comment by n-devr** [comment]
Per review with @bchiaruttini there are a few more small changes to be made:
 - [ ] Ensure that `Is child to be adopted as part of a sibling group?` and `Does child need contact with other siblings?` changes are included in the generated email
 - [ ] Remove the required (*) indicator from all fields on the edit form
 - [ ] Remove the paragraph from the bottom of the form
 - [ ] Update email subject to read: "Update to child registration"
 - [ ] Update email body to read: "An update has been submitted for: ..."
 - [ ] Remove `Considered` from `Medical or Developmental Needs Considered` field label

Let me know if I missed or misrepresented anything!

**Comment by bchiaruttini** [comment]
@n-devr In testing this, when I submit any change to a child update form, I get a pink error message:  There was an error editing this child registration.
If this error persists, please notify MARE at communications@mareinc.org

I did not get the same error when creating a new child record (although didn't get confirmation email so maybe these need to be turned back on to test?)  thanks.

**Comment by n-devr** [comment]
@bchiaruttini were you testing in development or production?  I did reset all of the email toggles in development so it won't send any emails by design, but I can update it so the email will be sent again if you'd like to run through it.

Also the staff contact for child registration emails is Kimberly Sheppard in production, so the emails will be sent to her if they are being generated.

**Comment by bchiaruttini** [comment]
@n-devr I was testing in development, correct?  I just tried again and got the same error message when attempting to submit an update to an existing record.

**Comment by n-devr** [comment]
@bchiaruttini I turned off the sending of emails in development after we did our initial testing - that's the default state for all email actions in development.  I can turn them back on, I just need to update some environment variables and redeploy the app in order to do so.  I'm happy to do so whenever, just let me know when you'd like to test and I can toggle/redeploy and let you know when it's ready.

**Comment by bchiaruttini** [comment]
@n-devr I'm free now if a good time to test? 

But I am not sure that this is the issue with the error message.  B/c when I submitted a new child registration I did not get the error (even though emails were off), but when I submitted an update I got the error message?

**Comment by bchiaruttini** [comment]
@n-devr tested out and changes all look good and ready to push.  Pls toggle off emails as well.

**Comment by n-devr** [comment]
Sounds good - email flag is toggled and development is rebuilding now.

**Comment by bchiaruttini** [comment]
@n-devr Sorry to hear you are not well today, and this can wait until your feeling better! But I am concerned that this code was not pushed to production.  When logged into production currently as a SW I only have the option to Register a Child, not update or work off a sibling that is already registered.  This looks correct in development (screenshot.)
![image](https://user-images.githubusercontent.com/37884165/73389638-a050b380-42a2-11ea-830f-52b7905371a2.png)

**Comment by bchiaruttini** [comment]
p.s. we have rec'd updates so this was working correctly at some point.

**Comment by n-devr** [comment]
Thanks @bchiaruttini - getting to rest today has already some good!

Does the SW account that you're logged in with have any children?  The update functionality is designed not display unless the SW has children to update.

**Comment by bchiaruttini** [comment]
@n-devr Ahhh, yes that is the issue, makes sense.  thanks.
