### ISSUE TITLE
Addition to Site Visitor records

### ISSUE THREAD

**Issue by bchiaruttini** [mareinc/mare#394]
Two additions to site visitor record to mimic behavior in other record types:

1.) When a child, family or SW record is created, the date of creation is noted at the bottom under history.  Would like for the same information to be available for site visitor records.
2.) Make visible list of inquiries associated with site visitor at bottom of their record.

**Comment by n-devr** [comment]
The date of creation for Site Visitors is currently being tracked (as of ~3 months ago) as I had to enable some of that functionality to support the Mailchimp integration.  Site Visitors that were created before the tracking code was added will not have `createdAt` and `updatedAt` fields, but any new Site Visitors will.  Hopefully that meets the requirements moving forward, but if we need to make additional changes to the older existing Site Visitor records we can discuss that as well.

**Comment by bchiaruttini** [comment]
looks good
