### ISSUE TITLE
MailChimp <-> Keystone List Sync Issue

### ISSUE THREAD

**Issue by joesmare** [mareinc/mare#398]
This story is a continuation of closed story #380 related to list sync issues.

@n-devr confirmed SW issue resolved and with the exception of 40+/- outliers the SW lists are now in sync.

@jeremysMARE will check, every 30 days. to assure that all users across a single list (either MM or Event) are maintaining synchronicity. If issues are observed then further investigation of the root cause ID'd in #380 will resume.

**Comment by joesmare** [comment]
@jeremysMARE based upon the recent list sync review, please manually sync the lists other than SW. @n-devr and I discussed this as establishing a baseline, as we did with SW. Please then continue to monitor for synchronicity and report any outliers going forward.

**Comment by bchiaruttini** [comment]
@jeremysMARE I believe this one is resolved as well?

**Comment by jeremysMARE** [comment]
@bchiaruttini Yes, this is resolved.
