### ISSUE TITLE
Fix child profile page display bug

### ISSUE THREAD

**Issue by jeremysMARE** [mareinc/mare#399]
When viewing the child profile gallery, if you search for a specific child, open their profile and then close it - their profile then populates in below the footer of the website.

**Comment by jeremysMARE** [comment]
<img width="600" alt="Screen Shot 2019-12-09 at 9 59 46 AM" src="https://user-images.githubusercontent.com/35849572/70446567-4a624b00-1a6b-11ea-94e2-51b9b9b31105.png">

**Comment by n-devr** [comment]
This is fixed and ready for review in dev.

**Comment by bchiaruttini** [comment]
tested and ready to push
