### ISSUE TITLE
Copy Updates - December

### ISSUE THREAD

**Issue by jeremysMARE** [mareinc/mare#400]
Change contact name in donation "thank you" message from Megan Dolan to Danielle Conti

**Comment by jeremysMARE** [comment]
@n-devr this copy update is now in development, and can be pushed to production in the next batch. @joesmare please note that this addresses Lisa's email regarding the donation thank you message.

**Comment by bchiaruttini** [comment]
@jeremysMARE just confirming we can close out this story?

**Comment by jeremysMARE** [comment]
If Noah can confirm that the changes were pushed from development to production, then yes we are set.
________________________________

**Comment by n-devr** [comment]
Looks like that commit is in prod 👍
