### ISSUE TITLE
Child registration content updates

### ISSUE THREAD

**Issue by n-devr** [mareinc/mare#403]
In reviewing the changes for the update child registration story @bchiaruttini identified a few content changes that should also be made to the new child registration form/flow to maintain consistency:

 - [x] Remove `Considered` from `Medical or Developmental Needs Considered` field label
 - [x] Make `register`, `add`, and `update` text bold in registration form header
 - [x] Update the title of the Register landing page to read "Register/Update"
 - [x] Update the button of the Register landing page to read "Register/Update"

**Comment by bchiaruttini** [comment]
@n-devr @joesmare all changes look good and ready to push to production.
