### ISSUE TITLE
Intermittent Log-in Error Messages 

### ISSUE THREAD

**Issue by joesmare** [mareinc/mare#405]
This is just a marker for the issue that we experienced today in case the behavior repeats in the future:

SW emailed to let us know that they were getting the redbox error at log-in using known credentials. This was validated by @joesmare using the test SW log-in credentials at production, on Chrome. @n-devr was not able to repeat the behavior, logging-in without any issue, as was @bchiaruttini . Upon several refreshes @joesmare was able to log-in. There was no issue with admin. or family log-in during this period.

**Comment by bchiaruttini** [comment]
captured elsewhere
