### ISSUE TITLE
MailChimp & Keystone Bounced Emails Solution

### ISSUE THREAD

**Issue by jeremysMARE** [mareinc/mare#419]
When keystone users have invalid emails that hard bounce in Mailchimp, updating the keystone email does not currently add their new email to Mailchimp. @n-devr is to write code that addresses this gap, so that whenever an email is updated for a user who can't be "found" in Mailchimp, the new keystone email will be added to as a subscriber to email lists as set in their keystone record.

Once completed the following process will be put into place to guide issue resolution:
1.	Jeremy will send a mass email to any users who are blocked from Mail Chimp (no likely response-used to seek out any further issues)
2.	Jeremy will educate CSC/FSS staff about the need for an individual user to update their email at the account level. This will trigger a response to re-add to Mail Chimp and reinstate emails.

**Comment by bchiaruttini** [comment]
@jeremysMARE not clear if this is still relevant given other changes?

**Comment by jeremysMARE** [comment]
@bchiaruttini The biggest take away from this, given all the other changes, is simply that when social workers are complaining that they don't receive MARE emails, the very first thing we should ask them to do is make sure the the email for their MARE account is up to date. Given that standing protocol, we can now close this issue.
