### ISSUE TITLE
addition of language to Child Update Form

### ISSUE THREAD

**Issue by bchiaruttini** [mareinc/mare#433]
Add question towards top of Child Registration UPDATE form : "Do you have an updated photo of this child?" with checkboxes for Yes and No, followed by statement "If yes, please email to web@mareinc.org".  these answers should reflect on the email generated in response to form submission, but (like all child update info) does not make an imprint in child record.

**Comment by bchiaruttini** [comment]
looks good - did not test it coming through in the update email as needs to be turned on.

**Comment by n-devr** [comment]
Great catch! I did test this on my local to make sure that it comes through, here's the email that was generated:
![image](https://user-images.githubusercontent.com/5726612/112211595-75d26000-8bf2-11eb-9369-bf753218811f.png)

I can also turn on those emails in `dev` if you'd like to test it yourself, just let me know!

**Comment by bchiaruttini** [comment]
okay that looks good - and data only come through if YES was selected, or if NO was selected too.

**Comment by n-devr** [comment]
The radio buttons on the form always default to 'No', so it should only register as an update when the user manually selects 'Yes'.
