### ISSUE TITLE
Additions to child registration form - out of state

### ISSUE THREAD

**Issue by bchiaruttini** [mareinc/mare#435]
Under "Does Child need  contact with other birth family", add mandatory questions:
Will consider out of state families from New England: Y or N
Will consider out of state families from any state :  Y or N

This data needs to be reflected as a field in the child's record.  This question should also be added to child update form.  This data does not need to be reportable.

**Comment by n-devr** [comment]
Makes sense @bchiaruttini - one question though: where would you these fields to display in the child record?

**Comment by bchiaruttini** [comment]
@n-devr   Under the question "does child need contact with other birthfamily?" in child record.

**Comment by bchiaruttini** [comment]
@n-devr tested this and all looks good in the form and the child record, however the information does not come through in the email that is generated...whether for new child registration or updates (as you note above).
