### ISSUE TITLE
Addition to Recruitment Options in Child Record - Weekend Family Connections

### ISSUE THREAD

**Issue by bchiaruttini** [mareinc/mare#460]
In child's record, under Recruitment Options:
When checkbox for Weekend Family Connections is checked the following should appear:
o	Date referred - prepopulate to today with manual override
o	Date visits started

Under Weekend Family Connections, add additional Child Recruitment Checkbox for "Specialized Recruitment Program", with check box for date referred.  This options should also be reflected in Child Listing Report with the other recruitment options.

**Comment by n-devr** [comment]
Updates to Child Record:
 - [ ] if WFC checked - date referred date field
 - [ ] if WFC checked - date visits started date field
 - [ ] "Specialized Recruitment Coordination" checkbox
    - [ ] when checked - date referred field (specialized recruitment date referred)

**Comment by n-devr** [comment]
@bchiaruttini this is deployed and ready for review in develop

**Comment by bchiaruttini** [comment]
looks perfect and ready to go - thanks.
