### ISSUE TITLE
Update adoption/recruitment worker agency selects to query based on agency code instead of name

### ISSUE THREAD

**Issue by bchiaruttini** [mareinc/mare#512]
Currently, in child listing report when selecting by adoption or recruitment worker agency, it is pulling from the agency name, not the agency code. Please change so that it is searchable by agency code.

**Comment by n-devr** [comment]
Should the rest of the Agency selects also be updated?  To date, all Agency selects have been set up to search by name.  I can update the existing implementations on previous reports as I go through and update the date range fields.

**Comment by bchiaruttini** [comment]
yes the rest of agency selects should also be updated. thanks

**Comment by n-devr** [comment]
Sounds good - because this task grew in scope to encompass more reports I'm gonna repurpose this story to more accurately capture the change we're making.  

I'm assuming that was it for the child-listing-specific fixes, but if there are more we can just make another story to capture those.

**Comment by n-devr** [comment]
@bchiaruttini this is ready for review in dev

**Comment by bchiaruttini** [comment]
looks great, ready to push!
