### ISSUE TITLE
Event Enhancement for Matching Events

### ISSUE THREAD

**Issue by bchiaruttini** [mareinc/mare#517]
Currently, in an event record, there is a checkbox for "matching event".  We need to first see if this has any functionality that we are not aware of, as to date it is just used as a checkbox, possibly for sorting.

Moving forward, if "matching meeting" is selected, it should disable child registration for any matching event. So a SW should be able to register themselves, but not be prompted to register specific children.

**Comment by n-devr** [comment]
@bchiaruttini this is ready to test on develop

**Comment by bchiaruttini** [comment]
just tested and ready to push
