### ISSUE TITLE
Adjust Default Columns in Inquiry List 

### ISSUE THREAD

**Issue by bchiaruttini** [mareinc/mare#537]
In Family Record, under Inquiries section, add "Type" and "Inquiry accepted" checkbox as default return column.  If too full and you need to delete a column, can remove source.

In Child Model, add "inquiry accepted" as default column.
In list of All Inquiries, add "inquiry accepted" as default column

**Comment by n-devr** [comment]
Default columns for Inquiry record:
- [ ] Type and Inquiry accepted should appear in Child/Family relationships sections
- [ ] Move taken by and source to the end of the default columns list

**Comment by bchiaruttini** [comment]
Looks good in Dev.
