### ISSUE TITLE
Add 5th Inquiry Type to list

### ISSUE THREAD

**Issue by bchiaruttini** [mareinc/mare#538]
Additional Inquiry type was added in the UI called "other point of engagement".  Needs to be hardcoded in the inquiry model.  And needs to be searchable in inquiry report as well.

**Comment by bchiaruttini** [comment]
@n-devr Tested in dev and looks good. the only glitch I see is if you are in the Inquiry Report, and search for all "points of engagement" type, you will see that the inquiry that you had entered yesterday displays the children that were originally associated with this inquiry, even when you have changed it back to Other Point of engagement 
![image](https://user-images.githubusercontent.com/37884165/97013719-5e922800-1517-11eb-9d09-b02afe654dba.png)

**Comment by n-devr** [comment]
@bchiaruttini that's the existing behavior of Inquiries - technically those children are still specified in the Inquiry record, they're just not visible in the admin ui.  If you create a child inquiry and switch it to a general inquiry (or any other inquiry type) the children aren't removed.  

That's something we could address in a `save` hook but IMO it's better left as a manual task.  Automating things like that can lead to data loss and confusion.
