### ISSUE TITLE
prevent models that need to exist from being deleted

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#60]
### as a developer, I need to prevent models that shouldn't be deleted from being deleted so that the website is more stable
---

### Tasks

- [ ] add `nodelete: true` to any model that will break the system if deleted

### Definition of Done

- [ ] models which the system relies on can't be deleted

### Notes

try adding this to a single model as well as the model definition to see how granularly we can restrict deletions.

**Comment by bchiaruttini** [comment]
would likely be an all or nothing by model.  would not address deleting individual records inadvertantly.  Closing
