### ISSUE TITLE
Family Listing Reporting

### ISSUE THREAD

**Issue by bchiaruttini** [mareinc/mare#615]
Create Family Report in Reporting Dashboard - May encompass 2nd Family Stages Report or create separately.

1.	Family Listing Report

Searchable in dashboard by: (and in this order):
Record created date – can use same ranges as child listing
Record created date by fiscal year – can mimic child listing
Homestudy verified/family can see all children – check box
Has an active database account – checkbox
Most Recent Stage - 
If stage is registered with MARE (even if not most recent), status
Family Constellation – multiple dropdown select 
Region – multiple dropdown select 
State – multiple dropdown select 
Contact 1 Gender - multiple dropdown select 
Contact 2 Gender - multiple dropdown select 
Contact 1 Race(s) - multiple dropdown select 
Contact 2 Race(s) - multiple dropdown select 
Social Worker - select name from dropdown, multiple select
Social Worker agency – select agency from dropdown by agency code, multiple select
Social Worker region – multiple dropdown select
Family Services (select from all options) - checkbox

Reportable fields in XLS (in addition to fields above): can provide full order for column spreadsheets?
Registration number
Email address
Contact 1 First Name
Contact 1 Last Name
Contact 1 Email Address
Contact 2 First Name
Contact 2 Last Name
Contact 2 Email Address 
Language
Other Language
Number of children currently in family
Number of other adults living in home
How did you hear about MARE
Date of all stages selected?

2.	Stages Report  - Selectable fields:
Has an active database account - checkbox
Record created date – can use same ranges as child listing?
Record created date by fiscal year – can mimic child listing?
	All of fields below would have ability to select AND/OR if input added
Homestudy verified/family can see all children – date range (before/after/between)
Initial Contact – date range (before/after/between)
Date info packet sent – date range (before/after/between)
gathering information - date range (before/after/between)
looking for agency - date range (before/after/between)
working with agency - date range (before/after/between)
MAPP training completed - date range (before/after/between)
homestudy completed - date range (before/after/between)
online matching - date range (before/after/between)
registered with MARE - date range (before/after/between)
family profile created - date range (before/after/between)
closed - date range (before/after/between)
Inquiry submitted date range (before/after/between)??

**Comment by bchiaruttini** [comment]
Here we go - hope I've got this right!

List #1: Fields to be displayed on the webpage search return, in order of priority from left to right:  
Registration number
Contact #1 First and Last Name
Contact #2 First and Last Name
Email address (account)
Most Recent Stage 
Family Constellation 
Region 
State 
Social Worker 
Social Worker agency
Social Worker region 
Contact 1 Gender - multiple dropdown select
Contact 2 Gender - multiple dropdown select
Contact 1 Race(s) - multiple dropdown select
Contact 2 Race(s) - multiple dropdown select

List #2: Fields to be hidden by default
Contact 1 Email Address
Contact 2 Email Address
Language
Other Language
Number of children currently in family
Number of other adults living in home


List #3: Order of fields to be reported left to right in Excel

**Comment by bchiaruttini** [comment]
List #3: Order of fields from L to R in Excel output:
Record created date – can use same ranges as child listing
Record created date by fiscal year – can mimic child listing
Homestudy verified/family can see all children – check box
Has an active database account – checkbox
Most Recent Stage -
If stage is registered with MARE (even if not most recent), status
Family Constellation – multiple dropdown select
Region – multiple dropdown select
State – multiple dropdown select
Contact 1 Gender - multiple dropdown select
Contact 2 Gender - multiple dropdown select
Contact 1 Race(s) - multiple dropdown select
Contact 2 Race(s) - multiple dropdown select
Social Worker - select name from dropdown, multiple select
Social Worker agency – select agency from dropdown by agency code, multiple select
Social Worker region – multiple dropdown select
Family Services (select from all options) - checkbox

Reportable fields in XLS (in addition to fields above): can provide full order for column spreadsheets?
Registration number
Email address
Contact 1 First Name
Contact 1 Last Name
Contact 1 Email Address
Contact 2 First Name
Contact 2 Last Name
Contact 2 Email Address
Language
Other Language
Number of children currently in family
Number of other adults living in home
How did you hear about MARE
Date of all stages selected?

**Comment by n-devr** [comment]
The remaining tasks and changes we discussed yesterday are deployed in dev and ready for review @bchiaruttini

**Comment by bchiaruttini** [comment]
good to push and will keep testing.

**Comment by bchiaruttini** [comment]
Some non-critical edits to this report, all related to XLS report:
1.) heading for Column P should read Family Registration Status
2.) In Column U (record created date), there are extra digits in the date format
3.) In columns AB-AH, can we change Not Started to Not Provided...this will just make more sense if they skip a step.

**Comment by bchiaruttini** [comment]
5.) Add Status (if HS registered) to selectable fields on website.

**Comment by bchiaruttini** [comment]
Change Record Created Date to initial contact date.
