### ISSUE TITLE
Mailchimp Email Lists

### ISSUE THREAD

**Issue by jeremysMARE** [mareinc/mare#628]
**Overall Description**
The current system that connects user accounts in Keystone to Mailchimp needs to be adjusted so that instead of populating 3 lists in Mailchimp, only one list is populated. Keystone will no longer be used to track email lists and user email subscriptions will not be synced between Keystone and Mailchimp. 

**Creating a User Account**
When a user creates a MARE account, the API should add that user email to the MailChimp Email list. Current account creation forms should have the option to select email preferences removed. Relevant tags should still be created for the subscriber in Mailchimp (family, social worker, etc).

We will also need some updates to the kinds of information imported from keystone when contacts are added to Mailchimp.:
1. Import state of residence to MailChimp
2. Tag new accounts marked in keystone as "gathering information" stage as "prospective family lead" (existing tag) in Mailchimp
3. Tag new accounts marked in keystone as "looking for agency" stage as "prospective family lead" (existing tag) in Mailchimp AND "prospective family lead - ready" (existing tag) in Mailchimp
4. Tag new accounts marked in keystone as "MAPP training completed" as  "MAPP training completed" (existing tag) in Mailchimp. Remove the following tags (if email already exists in Mailchimp) and do not create them (if new user): "gathering information", "prospective family lead", "looking for agency", "prospective family lead - ready", "prospective family lead - not ready", "prospective family lead - applied", "prospective family lead - not interested". Those tags should also be removed if account is updated to "MAPP training completed" via the admin UI.

5. Tag new accounts marked in keystone as "homestudy completed" as  "homestudy completed" (existing tag) in Mailchimp. Remove the following tags (if email already exists in Mailchimp) and do not create them (if new user): "gathering information", "prospective family lead", "looking for agency", "prospective family lead - ready", "prospective family lead - not ready", "prospective family lead - applied", "prospective family lead - not interested". Those tags should also be removed if account is updated to "homestudy completed" via the admin UI.

6. If a family account is marked as "closed" via the admin UI, they should be tagged as "closed" (new tag) in MailChimp upon save. 

**Unsubscribing**
In the MARE user account, they should still have the tab for "Mailing Lists". The options to select your mailing lists should be removed and replaced with two buttons:

Update Email Preferences 
This will prompt an automated transactional email, fetching the user email and sending them a MailChimp email (through Zapier integration) with a link to update their preferences. Upon clicking this link and entering their email, Mailchimp will send a confirmation email that they want to update their preferences, linking to a final form where they enter their preferences. 

Unsubscribe 
This will lead directly to MailChimp’s unsubscribe form: https://mareinc.us13.list-manage.com/unsubscribe?u=39a670129a9168e61f6cdd94c&id=573d45ceed

**Comment by jeremysMARE** [comment]
@bchiaruttini @n-devr Were you looking for any further description than what is listed here?

**Comment by bchiaruttini** [comment]
Sorry @jeremysMARE  - it was buried at the bottom of our long list so we missed it! Will bump up and defer to @n-devr if he has specific questions.

**Comment by jeremysMARE** [comment]
@n-devr In tandem with these changes, we will also need some updates to the kinds of information imported from keystone when contacts are added to Mailchimp. Highest priorities will be 1) state of residence 2)tag for "gathering information" 3) tag for "looking for agency"

Would it make the most sense to add these to the above updates or create other stories?

**Comment by n-devr** [comment]
### Updated tagging logic
 - [Family, Site Visitor, Social Worker] On creation, capture state of residence
     - Add tag(s): state abbreviation (e.g. `MA`, `NY`, `CO`)
     - Update on change: *TBD*
 - [Family] gathering information (checked)
     - Add tag(s): `prospective family lead`
     - Update on change: *TBD*
 - [Family] looking for agency (checked)
     - Add tag(s): `prospective family lead`, `prospective family lead - ready`
     - Update on change: *TBD*
 - [Family] MAPP training completed (checked)
     - Add tag(s): `MAPP training completed`
     - Remove tag(s): `gathering information`, `prospective family lead`, `looking for agency`, `prospective family lead - ready`, `prospective family lead - not ready`, `prospective family lead - applied`, `prospective family lead - not interested`
     - Update on change: *TBD*
 - [Family] homestudy completed (checked)
     - Add tag(s): `homestudy completed`
     - Remove tag(s): `gathering information`, `prospective family lead`, `looking for agency`, `prospective family lead - ready`, `prospective family lead - not ready`, `prospective family lead - applied`, `prospective family lead - not interested`
     - Update on change: *TBD*
 - [Family] closed (checked)
     - Add tag(s): `closed`
     - Update on change: *TBD*

**Comment by jeremysMARE** [comment]
@n-devr 

Copy for Email Preferences User Cases

1. Additional Standard Copy
If you would like to completely unsubscribe from all future MARE emails, please unsubscribe **here**.

For troubleshooting with email subscriptions, please contact web@mareinc.org for assistance.

2. Unsubscribed, Archived, or Deleted Users
You are currently not subscribed to our email list. If you would like to receive emails from MARE, please signup again by completing this Email Signup Form (http://eepurl.com/hkB4-X). _Note: Be sure to use the same email address as your MARE account._

3. Update Success message
Success!
Your email preferences have been successfully updated.

4. Update Error Message
Something Went Wrong
Please try updating your preferences again. If problems persist, please contact web@mareinc.org.

**Comment by jeremysMARE** [comment]
@n-devr In the current process, what happens if a MARE database account is deleted? Is the corresponding email unsubscribed from Mailchimp? Or does no change occur?

**Comment by n-devr** [comment]
No change occurs.  AFAIK there is no existing behavior based on models being deleted.

**Comment by jeremysMARE** [comment]
@n-devr Adding a note here, per our conversation, to check if keystone has a hook for when an account is deleted.

**Comment by n-devr** [comment]
@jeremysMARE I was actually able to get a hook firing when documents are removed from the database.  Let's discuss the behavior you'd like in this case - chances are I can probably make it work 👍🏻

**Comment by jeremysMARE** [comment]
@n-devr Great news! This should be relatively simple then. We want the email for any deleted account (of any type) to be unsubscribed from MailChimp.

**Comment by n-devr** [comment]
Got it, thanks Jeremy, I'll see what I can do!

**Comment by n-devr** [comment]
This is good to go @jeremysMARE .  Let me know if you want to test it out in `develop` and I'll turn on the flag to allow mailchimp updates so you can add/remove users.
