### ISSUE TITLE
Family Stages Report

### ISSUE THREAD

**Issue by bchiaruttini** [mareinc/mare#636]
Selectable fields on website:
Record created date – can use same ranges as child listing?
Record created date by fiscal year – can mimic child listing?

All of fields below would have ability to select ALL/ANY if input added:
Homestudy verified/family can see all children – date range (before/after/between)
Initial Contact – date range (before/after/between)
Date info packet sent – date range (before/after/between)
gathering information - date range (before/after/between)
looking for agency - date range (before/after/between)
working with agency - date range (before/after/between)
MAPP training completed - date range (before/after/between)
homestudy completed - date range (before/after/between)
online matching - date range (before/after/between)
registered with MARE - date range (before/after/between)
family profile created - date range (before/after/between)
closed - date range (before/after/between)
Inquiry submitted date range (before/after/between)??
Region
State
If stage is registered with MARE (even if not most recent), status

Reportable fields, in order of importance, first on web and then into xls:
Registration number (with hyperlink)
Email address (account)
Contact 1 First Name (first and last names combined on web return, separate in xls)
Contact 1 Last Name
Contact 2 First Name
Contact 2 Last Name
Most Recent Stage 
Region 
State 
Family Constellation 
Contact 1 Gender 
Contact 2 Gender
Contact 1 Race(s) 
Contact 2 Race(s) 
Contact 1 Email Address
Contact 2 Email Address
Social Worker 
Social Worker agency 
Social Worker region
Language
Other Language
Number of children currently in family
Number of other adults living in home
How did you hear about MARE
Family Services 
Homestudy verified/family can see all children 
Has an active database account 
Date of all stages selected (from list above, including record created date)
Has an active database account - checkbox

**Comment by n-devr** [comment]
This is ready for review in develop @bchiaruttini 

I still need to implement the PDF export but I wasn't sure which columns you wanted include - let me know and I'll get that taken care of as well!

**Comment by bchiaruttini** [comment]
great thanks @n-devr Noah.  I took a quick look and will continue to test out tomorrow, but the "required" button seems to be working great thus far.   As for the columns in the PDF export, it looks good as is - the only one missing is Family Status (which is also missing from column visibility)

And as for your earlier question regarding hyperlinking in XLS, I see you are correct that we haven't done this in past reports. I must have been confusing with the hyperlink on the web return, so that's all good.

**Comment by bchiaruttini** [comment]
Changes to Family Listing:
1.) Add Family Status as field for column visibility and XLS export.
2.) Update icon on List of Reports 
3.) Question - was "any" in date range changed to 1995?
4.) Remove online matching as a stage on website (unless it throws off balance then can leave.) Okay if it is in XLS export.
