### ISSUE TITLE
Create Manual Entry option on matching reports (and add additional columns)

### ISSUE THREAD

**Issue by bchiaruttini** [mareinc/mare#648]
On Child Matching Report and Family Matching Report, add Anonymous Child and Anonymous Family as the first option that displays on the list.  These should default to the broadest range of families/children with ability to manually set criteria.  

Should not have option to Save entries to Family/Child.

Additionally, in child matching report export, add column for family's worker, family's worker agency, and family's worker email address.

**Comment by n-devr** [comment]
@bchiaruttini family/child matching reports have both been updated to support anonymous users, ready to test in `dev`!

**Comment by bchiaruttini** [comment]
tested and all looks good, ready to push to prod.

**Comment by bchiaruttini** [comment]
found one issue on this change. When using Anonymous Child in Child matching report, the dropdowns for the fields "other considerations" and "disabilities" are not present.

**Comment by bchiaruttini** [comment]
tested and looks good.
