### ISSUE TITLE
Ability to track caseload on given date

### ISSUE THREAD

**Issue by bchiaruttini** [mareinc/mare#651]
include in chron job ability to capture the data currently in regional counts dashboard, such that you could recall it to track caseload at a given point in time (and average over a time range?).  

Also, capture number of children with "activate child profile on website" selected at given point in time (and average over a time range?) along with legal status of child.  (could achieve story #502 and #195?)

**Comment by bchiaruttini** [comment]
could also combine with chron job story #317 while at it?

**Comment by n-devr** [comment]
Per discussion with Bridget:
- [ ] Add a count of all children who are active on website and also a legal risk
