### ISSUE TITLE
Menu Changes - About Us

### ISSUE THREAD

**Issue by jeremysMARE** [mareinc/mare#666]
Restructure menu items under "About Us"

New top item: Who We Are
	Page should include the following content:
Mission and Vision (see attached revisions)
Racial Equity Statement
New Item: What We Do
"Our Services" - text currently on Mission and Vision Page
History (see attached revisions)
MARE in the News Links (minimal)
Meet the Staff
Board of Directors
Annual Report
Careers

New Menu Item Under "Considering Adoption?"
Adoption Stories (last item listed in menu)

The bottom left "bucket" on the MARE homepage should link to the racial equity statement and have a simple graphic or photo to match.

Add COVID response page link to text of "How Does MARE Support Families" and "How Does MARE Help Social Workers"

**Comment by jeremysMARE** [comment]
Further revisions based on presentation on the development server:
- Revise location of racial equity statement anchor link. Currently, when following the link from the MARE homepage, the top of the statement is cutoff when the page loads.
- I added additional content in the Our Services section, which should be included in the final version pushed to production
- MARE in the News doesn't seem to be presenting correctly - the content is squished to the left

**Comment by isahmare** [comment]
All set!

**Comment by n-devr** [comment]
Just a heads up, this release is going to require a bit of coordination between the three of us.  All of the changes that've been made in Keystone on `develop` will need to be duplicated in `production`, at which point I can push the code changes to `production` and kick off a new build.

**Comment by isahmare** [comment]
All set! Added in the 2 new pages.
