### ISSUE TITLE
Improve flexibility of Featured Items on homepage

### ISSUE THREAD

**Issue by bchiaruttini** [mareinc/mare#686]
On home page of website, need ability for more diverse content in each of the three Featured Items (currently events, adoption stories and racial equity).  Each featured item should have ability to point to an event, and adoption story, a mare webpage OR a third party url.  All three should be editable within keystone.

**Comment by n-devr** [comment]
@jeremysMARE the new Featured Item models are live in production - ready for a final review before we close this one out.

**Comment by jeremysMARE** [comment]
I see this in production, but the the items in the backend don't seem to match what is currently presented on the front end?
________________________________
