### ISSUE TITLE
Issues with SW Inquiries on behalf of families.

### ISSUE THREAD

**Issue by bchiaruttini** [mareinc/mare#706]
Several confusing behaviors when a SW inquirers about a child on behalf of a family.  Current behavior is we prompt SW to enter a text box naming the family they are inquiring on behalf of, and then the admin needs to go in and manually connect to family if they have a record

1.) Currently, when viewing an inquiry, it defaults to the "Is the family registered" box being checked, whether or not the family is in fact registered, which masks the text entered in text box upon submitting inquiry.  Should not default to registered, only if admin manually changes.  

2.) In inquiry list in Keystone (under inquiries or in child record), is it possible to change column of "family" to "user" and reflect if a SW or Family submitted the inquiry? Right now if a SW submits an inquiry, the Family column is empty as not connected to the "on behalf of" family

3.) If SW provides name of family and they are registered, and admin links to the registered family's account, can the inquiry appear in the family's record, reflecting that submitted by their worker?

**Comment by n-devr** [comment]
Unfortunately item 2 is not possible without an update to the core functionality of Keystone.
