### ISSUE TITLE
Ability to track all families served over a specific period of time

### ISSUE THREAD

**Issue by bchiaruttini** [mareinc/mare#733]
Define a list of actions of families/family records that would constitute activity and then track the most recent activity.  Need to be able to query by date in Keystone.

Family Activities should include:
-New Account creation (could add to Fam Stages)
-Anything in change history?
-Event Registration
-Inquiry
-Match/Placement
-Internal Note

Needs to be searchable by town/region/LGBTQ status, relationship status, etc.

XL export: email, most recent date it happened on, gender

**Comment by n-devr** [comment]
### Review with Jeremy
- [ ] update column values to link to the database record they represent
- [ ] fix date sorting for any date-driven columns
- [ ] add gender and race to search form
- [ ] add last 3 fiscal year buttons to search form
- [ ] if possible, capture latest bookmark for child and sibling group

**Comment by n-devr** [comment]
Review Tasks from discussion with @jeremysMARE
- [ ] replace state field with city/town field
- [ ] update max results returned logic to display accurately based on pre-filtered result count
- [ ] implement excel export
- [ ] implement form reset
- [ ] capture bookmark activity

**Comment by n-devr** [comment]
Review Tasks from discussion with @jeremysMARE
 - [ ] combine gender selects into a single select
 - [ ] combine race selects into a single select
 - [ ] combine LGBTQ+ identity selects into a single select
 - [ ] add contact 1 & 2 race columns to Excel export
 - [ ] add contact 1 & 2 LGBTQ+ identity columns to Excel export
 - [ ] update name of report to "Families Served"
 - [ ] update registration date column to "Account Creation Date" on website table and Excel export
 - [ ] update "Total Active Families" label to read "Total Families Served"
 - [ ] move "Total Families Served" to display under "Results:" and increase font size to 24px
 - [ ]

**Comment by jeremysMARE** [comment]
- [ ] Add region to excel export
- [ ] Add town to excel export

**Comment by jeremysMARE** [comment]
@n-devr When filtering results by region, the report now seems to show no results no matter the combination of filters applied. The region does appear in the excel export for the same data, however. 

For instance: Searching for families served the last fiscal year shows results and when exported to excel, the region is represented for all families. However, if you filter those results in the report by any region, it produces no results.
