### ISSUE TITLE
SOGIE data for families

### ISSUE THREAD

**Issue by bchiaruttini** [mareinc/mare#735]
Goal is to collect family constellation and LGBTQ data upon account creation and limit existing family constellation choices to single or partnered.

For LGBTQ status, add non-mandatory questions:  Do you identify as part of the LGBTQ+ community with options of Y, N, Do not wish to answer and comment box.  Selection and comments viewable in record in keystone.

For family constellation:
-Add mandatory question upon account creation: Are you single or partnered? With drop down options, single, partnered, Unknown/Don't with to share
-Run script to change all single gay and male/male and female/female to have LGBTQ checkbox selected Y.  Then change all previous single (gay male, gay female, straight female, straight male, male, female) to be single, and all previous couple combos to be couple. Unknown should remain as an option and no migration needed if unknown is selection

**Comment by n-devr** [comment]
@bchiaruttini SOGIE updates for families are complete and the script has been run to update all of the family constellation data in `develop`.

**Comment by bchiaruttini** [comment]
@n-devr We can discuss this afternoon but I did some spot testing and don't see any families in dev where the LGBTQ identity is selected. (unless this is a second separate script?) A few examples that didn't look as I would have expected are:

Aaron and Imre Rainey-Spence - 30593
Adrien Pike and Joseph Sparr - 40086
