### ISSUE TITLE
Mini-Design of Inquiries List in Family Record

### ISSUE THREAD

**Issue by bchiaruttini** [mareinc/mare#744]
Under Title of Inquiries, add _These are the inquiries associated with your account. Personal notes you add are not shared and are viewable only by you._

Configure list of Inquiries in Family's My Information are so that they are easier to view and scan.  Ideally present as more linear, with fields of
**Date Submitted: 10/21/2006
Inquiry Type: child inquiry
Children: Julius (6381), Armani (6382)
Inquiry Comments: Please send more info**

remaining in left column and Family Comments (with instruction to enter personal notes here) on the right. Consider a different color text for the content that the family adds?

**Comment by n-devr** [comment]
Ensure extremely long strings in the Inquiry Comments section wrap or truncate.
<img width="1676" alt="image" src="https://user-images.githubusercontent.com/5726612/160908486-b68094ba-2c5a-43a0-ac2f-6c7d46cd4bef.png">

**Comment by jeremysMARE** [comment]
Design Changes.

Reformat to something similar below:

Child Inquiry  [title of type of inquiry] (use heading format from Events listing page for event titles)
[line break]
Date Submitted (align with Personal Note on the right hand side)
Children: [names of children]
Inquiry Comments
[line break]
[line break]
Save Button

**Comment by n-devr** [comment]
Add conditional "On behalf of" field below "Children" field
