### ISSUE TITLE
Changes in Reporting related to Family SOGIE

### ISSUE THREAD

**Issue by bchiaruttini** [mareinc/mare#747]
Think through implications in change to Family Constellation in other functionality:
1.) Child Matching - family constellations will be single and partnered

2.) Child Registration/Update - Under recommended family constellations, options will be single and partnered, 

3.) Child Profile search

Possible option: have additional constellation options that are hidden upon account creation (and in family record?), but visible for Child Reg/matching/keystone record. Options would be: Requires one female parent?? Requires only female parents??

**Comment by bchiaruttini** [comment]
Suggested list of family constellation and other family constellation:

Two-parents REQUIRED
Female parent REQUIRED
Male parent REQUIRED
Childless home REQUIRED
No older children
No younger children
CANNOT be placed with pets

**Comment by n-devr** [comment]
Converting to exclusion fields per discussion with Bridget:

### Family Constellation Exclusions
 - Must not be placed in a single-parent household
 - Must not be placed with female parent(s)
 - Must not be placed with male parent(s)

### Other Exclusions
 - Must not be placed in a home with children
 - Must not be placed with older children
 - Must not be placed with younger children
 - Must not be placed in a home with pets

**Comment by n-devr** [comment]
- [ ] Update `Placement Exclusions (check all that apply)` text to `Child CANNOT be placed with (check all that apply)`
 - [ ] Add yellow highlight to exclusions fields on child update form
