### ISSUE TITLE
Change to Placement Report

### ISSUE THREAD

**Issue by bchiaruttini** [mareinc/mare#755]
Add LGBTQ+ identified to placement report output.

**Comment by n-devr** [comment]
per review with @jeremysMARE :
- [ ] Add LGBTQ+ identity column for family contact 1 on Excel export
- [ ] Add LGBTQ+ identity column for family contact 2 on Excel export

**Comment by bchiaruttini** [comment]
hi @n-devr @jeremysMARE! Were starting to use these end of year reports, so caught one more change we need to make to placement report.  The column visibility and XL export are still showing archived 'family constellation' field, and show show 'single or partnered' field.  Can we update this in both spots?  thanks.
