### ISSUE TITLE
Add tags in Mailchimp for Out of State and NE/NY families

### ISSUE THREAD

**Issue by jeremysMARE** [mareinc/mare#757]
Create additional logic when family accounts are created or the state of residence in their account is updated to add/remove tags in Mailchimp. All families outside MA should be tagged "Out of State". All families in Maine, New Hampshire, Vermont, Conneticut, Rhode Island, and New York should be tagged "NE/NY". These tags already exist in Mailchimp.

**Comment by n-devr** [comment]
- [ ] Once new tagging logic is reviewed and approved, run a script to update all families' tags to ensure consistency between Mailchimp and Keystone

**Comment by jeremysMARE** [comment]
@n-devr Currently the script seems to apply the NE/NY tag to those in Massachusetts (when updating an account in keystone from admin). We don't want this tag for MA residents.

**Comment by n-devr** [comment]
Gotcha - I thought the tags were mutually exclusive.  The logic is updated and ready for review.

**Comment by jeremysMARE** [comment]
For some reason there seems to be a consistency issue for the "out of state" tag when updating an account in Keystone. The tag seems to always apply properly if updating to a new england state, but doesn't apply if updating the record to a non NE/NY state. When updating a record from another state to Massachusetts, if the tag was already applied, the logic sometimes leaves the out of state tag on a Massachusetts family.


________________________________
