### ISSUE TITLE
Inquiry Process for Out of State Families

### ISSUE THREAD

**Issue by jeremysMARE** [mareinc/mare#805]
Create a new inquiry process flow for out of state families inquiring about children through MARE web. All non-new england (and new york) families should be directed to a different inquiry page, which will prompt them to have their social worker submit an inquiry on their behalf. The process for in-state inquiries should stay the same. 

Out of State Inquiry Page Copy:
Thank you for your interest in waiting youth from Massachusetts!

It looks like you live outside of New England. If you have a current homestudy and are licensed to adopt from foster care in your home state, you are eligible to receive additional information about waiting youth. However, we ask that your social worker submit child inquiries through the MARE website on your behalf. Please note that we do not accept child inquiries directly from families that live outside of New England.

Your social worker can create an account with us by following this link: XXXXX. Once their account has been approved, they will be able to receive and share with you additional information about waiting Massachusetts youth.

For questions about creating a social worker account, please contact Ricardo Franco, Director of Family Support Services, at [ricardof@mareinc.org](mailto:ricardof@mareinc.org).

If you are not yet licensed to adopt from foster care and would like to learn more, please visit https://www.adoptuskids.org/ . You can learn more about specific licensing requirements in your home state here: https://www.adoptuskids.org/adoption-and-foster-care/how-to-adopt-and-foster/state-information

**Comment by jeremysMARE** [comment]
Program Staff Notes:

- do we have an easy way to invite someone else to create an account?
- create instructions for social workers to create account/inquire

**Comment by jeremysMARE** [comment]
@n-devr Moving this to backlog, as the program staff would like to move forward with it.

**Comment by n-devr** [comment]
### Tasks
 - [ ] Update routing logic to catch out of state families and redirect them away from the existing Inquiry page
 - [ ] Create new page Inquiry page for out of state families
