### ISSUE TITLE
Social Worker Field From Family Account Creation Need to be Represented on Family Record

### ISSUE THREAD

**Issue by jeremysMARE** [mareinc/mare#811]
When a family creates an account and is a homestudied family, they should be prompted to enter homestudy date, and "Social Worker Name & Email". The information submitted in the "Social Worker Name & Email" field should be entered on the family record, under the checkbox "Social worker isn't listed"

**Comment by n-devr** [comment]
### Tasks
- [ ] if Homestudy completed is checked, set social worker name on family record in the corresponding text entry field (non-relationship)
 - [ ] if Homestudy completed is checked, set social worker email on family record in the corresponding text entry field (non-relationship)

**Comment by jeremysMARE** [comment]
@n-devr Ready for production! Once it is pushed I will close the issue.
