### ISSUE TITLE
Prevent Duplicate Record Creation in HubSpot/Keystone Integration

### ISSUE THREAD

**Issue by jeremysMARE** [mareinc/mare#846]
Social worker accounts in keystone without emails are being repetitively duplicated in Hubspot as contacts. Presumably the integration is looking to see if the contact already exists in Hubspot by checking the email value as a unique ID. Since there is no email value, it creates a new contact every time the keystone record is saved or some other process is carried out.

Most of the social worker records I've inspected in Keystone have not been edited recently, so I'm not sure what is triggering the contact creation in HubSpot.

**Comment by n-devr** [comment]
This *should* be working now, please let me know if it's still not preventing duplicates!

**Comment by jeremysMARE** [comment]
I don't see any duplicates after 3/21, but I will keep this open for the next week to be sure.
