### ISSUE TITLE
add stage in the process to the family account confirmation email

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#85]
### as a developer, I need to update the contents of the family account confirmation email so that CSCs can see the relevant steps in the process information
---

### Tasks

- [ ] add the most recent stage under a **steps in the process** header.  The most recent date ( to the day ) should take precedence, and if two stages have the same date, it should use the stage that's furthest along in the process.

### Definition of done

- [ ] the most recent stage is displayed under **steps in the process**.  The most recent date (to the day) takes precedence, and if two stages have the same date, it shows the stage that's furthest along in the process.

**Comment by bchiaruttini** [comment]
Upon exploration by Neptune, this was already resolved.
