### ISSUE TITLE
constellation options should be selected by default when registering children in the admin UI

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#87]
### as a developer, I need to select the family constellation options by default so that CSCs don't need to spend as much time when creating new child records
---

### Tasks

- [ ] update the family constellation field to have all options selected by default

### Definition of Done

- [ ] when creating a new child in the admin UI, all family constellations are selected by default

### Notes

This may not be possible at the field level or at all.  Consider handling it in a lifecycle hook.

**Comment by bchiaruttini** [comment]
Loading all family constellations takes a great deal of time and users are frequently kicked out of the record while waiting for them all to load.  After being kicked out, it sometimes results in deleting other fields (for example profile paragraphs) that had previously been saved during the same session.
