### ISSUE TITLE
conditionally update the header for the adoption preferences section of the family account creation form

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#89]
In family account creation form, only display Adoption Preferences section, if family stage selected is MAPP Training Completed, or Homestudy Completed.  If any of the other three stages, user should not see these options. 

Additional and unrelated small change to this form: For field "Number of other adults living in home" change to "Number of OTHER adults living in home (not listed above)".  (Does not need to change in UI, people are just not understanding the question as written)

**Comment by n-devr** [comment]
@bchiaruttini the current behavior of the family registration form is to require the fields in the `Adoption Preferences` section when `Working with an agency` is checked.  If I'm reading the requirements correctly, that section would remain hidden even if `Working with an agency` is checked but `MAPP Training Completed` or `Homestudy Completed` aren't checked. 
Should I remove the required behavior for `Working with an agency`, or add `Working with an agency` to the list of options that displays the `Adoption Preferences` fields?

**Comment by n-devr** [comment]
Updated and ready for testing in `develop`!

**Comment by bchiaruttini** [comment]
looks perfect, ready to push.
